// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://poeticmetric.com/terms-of-service",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/authentication/change-user-password": {
            "post": {
                "security": [
                    {
                        "BasicAuthentication": []
                    }
                ],
                "description": "Change currently authenticated user's password.",
                "tags": [
                    "authentication"
                ],
                "summary": "Change password",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    }
                }
            }
        },
        "/authentication/organization": {
            "get": {
                "security": [
                    {
                        "UserAccessTokenAuthentication": []
                    }
                ],
                "description": "Read currently authenticated user's organization.",
                "tags": [
                    "authentication"
                ],
                "summary": "Read organization",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.AuthenticationOrganization"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "UserAccessTokenAuthentication": []
                    }
                ],
                "description": "Update currently authenticated user's organization.",
                "tags": [
                    "authentication"
                ],
                "summary": "Update organization",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.AuthenticationOrganization"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    }
                }
            }
        },
        "/authentication/reset-user-password": {
            "post": {
                "description": "Reset user's password also deleting all existing user access tokens for that user.",
                "tags": [
                    "authentication"
                ],
                "summary": "Reset user's password",
                "parameters": [
                    {
                        "description": "Params",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.ResetUserPasswordParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.ResetUserPasswordParams"
                        }
                    }
                }
            }
        },
        "/authentication/send-user-password-recovery-email": {
            "post": {
                "description": "Send a password recovery e-mail to the user.",
                "tags": [
                    "authentication"
                ],
                "summary": "Send user password recovery e-mail",
                "parameters": [
                    {
                        "description": "Params",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.SendUserPasswordRecoveryEmailParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    }
                }
            }
        },
        "/authentication/user": {
            "get": {
                "security": [
                    {
                        "UserAccessTokenAuthentication": []
                    }
                ],
                "description": "Read currently authenticated user.",
                "tags": [
                    "authentication"
                ],
                "summary": "Read user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.AuthenticationUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "UserAccessTokenAuthentication": []
                    }
                ],
                "description": "Update currently authenticated user.",
                "tags": [
                    "authentication"
                ],
                "summary": "Update user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.AuthenticationUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    }
                }
            }
        },
        "/authentication/user-access-tokens": {
            "post": {
                "security": [
                    {
                        "BasicAuthentication": []
                    }
                ],
                "description": "Create a user access token by authenticating with the e-mail address and password.",
                "tags": [
                    "authentication"
                ],
                "summary": "Create user access token",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.AuthenticationUserAccessToken"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "UserAccessTokenAuthentication": []
                    }
                ],
                "description": "Delete user access token currently in use.",
                "tags": [
                    "authentication"
                ],
                "summary": "Delete user access token",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    }
                }
            }
        },
        "/bootstrap": {
            "get": {
                "description": "check if the bootstrap process is already done.",
                "tags": [
                    "boostrap"
                ],
                "summary": "Check bootstrap status",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "check if the bootstrap process is already done.",
                "tags": [
                    "boostrap"
                ],
                "summary": "Run bootstrap",
                "parameters": [
                    {
                        "description": "Params",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.BootstrapServiceRunParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/sites": {
            "get": {
                "security": [
                    {
                        "UserAccessTokenAuthentication": []
                    }
                ],
                "description": "List sites.",
                "tags": [
                    "sites"
                ],
                "summary": "List sites",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/poeticmetric.OrganizationSite"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "UserAccessTokenAuthentication": []
                    }
                ],
                "description": "Create site.",
                "tags": [
                    "sites"
                ],
                "summary": "Create site",
                "parameters": [
                    {
                        "description": "Params",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.CreateSiteParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.OrganizationSite"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "UserAccessTokenAuthentication": []
                    }
                ],
                "description": "List users.",
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/poeticmetric.OrganizationUser"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "UserAccessTokenAuthentication": []
                    }
                ],
                "description": "Invite a new user to organization.",
                "tags": [
                    "users"
                ],
                "summary": "Invite user",
                "parameters": [
                    {
                        "description": "Params",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/poeticmetric.InviteOrganizationUserParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/poeticmetric.OrganizationUser"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "poeticmetric.AuthenticationOrganization": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "poeticmetric.AuthenticationUser": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isEmailVerified": {
                    "type": "boolean"
                },
                "isOrganizationOwner": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "poeticmetric.AuthenticationUserAccessToken": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "poeticmetric.BootstrapServiceRunParams": {
            "type": "object",
            "properties": {
                "createDemoSite": {
                    "type": "boolean"
                },
                "organizationName": {
                    "type": "string"
                },
                "userEmail": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userPassword": {
                    "type": "string"
                },
                "userPassword2": {
                    "type": "string"
                }
            }
        },
        "poeticmetric.CreateSiteParams": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "googleSearchConsoleSiteURL": {
                    "type": "string"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "safeQueryParameters": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "poeticmetric.InviteOrganizationUserParams": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "poeticmetric.OrganizationSite": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "googleSearchConsoleSiteURL": {
                    "type": "string"
                },
                "hasEvents": {
                    "type": "boolean"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "safeQueryParameters": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "poeticmetric.OrganizationUser": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isEmailVerified": {
                    "type": "boolean"
                },
                "isOrganizationOwner": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "poeticmetric.ResetUserPasswordParams": {
            "type": "object",
            "properties": {
                "passwordResetToken": {
                    "type": "string"
                },
                "userPassword": {
                    "type": "string"
                },
                "userPassword2": {
                    "type": "string"
                }
            }
        },
        "poeticmetric.SendUserPasswordRecoveryEmailParams": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "responder.DetailResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Human-readable detail of the response.",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuthentication": {
            "type": "basic"
        },
        "UserAccessTokenAuthentication": {
            "description": "User access token authentication.",
            "type": "apiKey",
            "name": "authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "PoeticMetric REST API",
	Description:      "This is a REST API for PoeticMetric.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
