// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://poeticmetric.com/terms-of-service",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bootstrap": {
            "get": {
                "description": "check if the bootstrap process is already done",
                "tags": [
                    "boostrap"
                ],
                "summary": "Check bootstrap status",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responder.DetailResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "check if the bootstrap process is already done",
                "tags": [
                    "boostrap"
                ],
                "summary": "Run bootstrap",
                "parameters": [
                    {
                        "description": "Params",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/analytics.BootstrapServiceRunParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        }
    },
    "definitions": {
        "analytics.BootstrapServiceRunParams": {
            "type": "object",
            "properties": {
                "createDemoSite": {
                    "type": "boolean"
                },
                "organizationName": {
                    "type": "string"
                },
                "userEmail": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "userPassword": {
                    "type": "string"
                },
                "userPassword2": {
                    "type": "string"
                }
            }
        },
        "responder.DetailResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Human-readable detail of the response.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "PoeticMetric REST API",
	Description:      "This is a REST API for PoeticMetric.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
