version: "3.9"

x-backend-common: &go-common
  build:
    context: .
    dockerfile: development.Dockerfile
  image: ghcr.io/th0th/poeticmetric
  environment: &go-common-environment
    BASE_URL: ${BASE_URL}
    CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE}
    CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
    CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    CLICKHOUSE_PORT: ${CLICKHOUSE_PORT}
    CLICKHOUSE_USER: ${CLICKHOUSE_USER}
    DEBUG: ${DEBUG}
    GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    POSTGRES_HOST: ${POSTGRES_HOST}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_PORT: ${POSTGRES_PORT}
    POSTGRES_USER: ${POSTGRES_USER}
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PASSWORD: ${REDIS_PASSWORD}
    REDIS_PORT: ${REDIS_PORT}
  restart: unless-stopped
  volumes:
    - ./cmd:/poeticmetric/cmd
    - ./internal:/poeticmetric/internal
    - ./migrations:/poeticmetric/migrations
    - ./public:/poeticmetric/public
    - ./public-generated:/poeticmetric/public-generated
    - ./templates:/poeticmetric/templates
    - ./go.mod:/poeticmetric/go.mod
    - ./go.sum:/poeticmetric/go.sum
    - ./MANIFESTO.md:/poeticmetric/MANIFESTO.md

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}

volumes:
  clickhouse:
  postgres:
  redis:

services:
  clickhouse:
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DATABASE}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
    image: clickhouse/clickhouse-server:latest-alpine
    ports:
      - "127.0.0.1:8123:8123"
    volumes:
      - clickhouse:/var/lib/clickhouse

  mailpit:
    environment:
      VIRTUAL_HOST: mailpit.dev.poeticmetric.org
      VIRTUAL_PORT: "8025"
    image: axllent/mailpit:v1.8.2

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./etc/ssl:/etc/nginx/certs:ro

  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  #  rabbitmq:
  #    environment:
  #      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  #      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
  #      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
  #      VIRTUAL_HOST: rabbitmq.dev.poeticmetric.com
  #      VIRTUAL_PORT: "15672"
  #    image: rabbitmq:3-management-alpine
  #    ports:
  #      - "127.0.0.1:15672:15672"

  redis:
    command:
      - "redis-server"
      - "--requirepass"
      - "${REDIS_PASSWORD}"
    image: redis:7-alpine
    volumes:
      - redis:/data

  #  scheduler:
  #    <<: *go-common
  #    environment:
  #      <<: *go-common-environment
  #      INSTANCE: scheduler

  webapp:
    <<: *go-common
    environment:
      <<: *go-common-environment
      INSTANCE: webapp
      VIRTUAL_HOST: dev.poeticmetric.com

#  worker:
#    <<: *go-common
#    environment:
#      <<: *go-common-environment
#      INSTANCE: worker
