linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - prealloc
    - staticcheck
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain

version: "2"
