#!/usr/bin/env bash
set -eo pipefail

exec migrate \
  -database "clickhouse://${CLICKHOUSE_HOST}:${CLICKHOUSE_TCP_PORT}?username=${CLICKHOUSE_USER}&password=${CLICKHOUSE_PASSWORD}&database=${CLICKHOUSE_DATABASE}&x-multi-statement=true" \
  -source "file:///poeticmetric/migrations/clickhouse" \
  "$@"
