#!/usr/bin/env bash
set -eo pipefail

exec migrate \
  -database "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable" \
  -source "file:///poeticmetric/migrations/postgres" \
  "$@"
