#!/usr/bin/env bash
set -eo pipefail

exec migrate \
  -database "postgres://${POETICMETRIC_POSTGRES_USER}:${POETICMETRIC_POSTGRES_PASSWORD}@${POETICMETRIC_POSTGRES_HOST}:${POETICMETRIC_POSTGRES_PORT}/${POETICMETRIC_POSTGRES_DATABASE}?sslmode=disable" \
  -source "file:///poeticmetric/migrations/postgres" \
  "$@"
