package poeticmetric

import (
	"sync"
)

var countryISOCodeNameMap map[string]string
var timeZoneCountryISOCodeMap map[string]string

func CountryISOCodeNameMap() map[string]string {
	if countryISOCodeNameMap == nil {
		setCountryISOCodeNameMapOnce()
	}

	return countryISOCodeNameMap
}

func TimeZoneCountryISOCodeMap() map[string]string {
	if timeZoneCountryISOCodeMap == nil {
		setTimeZoneCountryISOCodeMapOnce()
	}

	return timeZoneCountryISOCodeMap
}

func setCountryISOCodeNameMap() {
	countryISOCodeNameMap = map[string]string{
		"ABW": "Aruba",
		"AFG": "Afghanistan",
		"AGO": "Angola",
		"AIA": "Anguilla",
		"ALA": "Åland Islands",
		"ALB": "Albania",
		"AND": "Andorra",
		"ARE": "United Arab Emirates (the)",
		"ARG": "Argentina",
		"ARM": "Armenia",
		"ASM": "American Samoa",
		"ATA": "Antarctica",
		"ATF": "French Southern Territories (the)",
		"ATG": "Antigua and Barbuda",
		"AUS": "Australia",
		"AUT": "Austria",
		"AZE": "Azerbaijan",
		"BDI": "Burundi",
		"BEL": "Belgium",
		"BEN": "Benin",
		"BES": "Bonaire, Sint Eustatius and Saba",
		"BFA": "Burkina Faso",
		"BGD": "Bangladesh",
		"BGR": "Bulgaria",
		"BHR": "Bahrain",
		"BHS": "Bahamas (the)",
		"BIH": "Bosnia and Herzegovina",
		"BLM": "Saint Barthélemy",
		"BLR": "Belarus",
		"BLZ": "Belize",
		"BMU": "Bermuda",
		"BOL": "Bolivia (Plurinational State of)",
		"BRA": "Brazil",
		"BRB": "Barbados",
		"BRN": "Brunei Darussalam",
		"BTN": "Bhutan",
		"BVT": "Bouvet Island",
		"BWA": "Botswana",
		"CAF": "Central African Republic (the)",
		"CAN": "Canada",
		"CCK": "Cocos (Keeling) Islands (the)",
		"CHE": "Switzerland",
		"CHL": "Chile",
		"CHN": "China",
		"CIV": "Côte d'Ivoire",
		"CMR": "Cameroon",
		"COD": "Congo (the Democratic Republic of the)",
		"COG": "Congo (the)",
		"COK": "Cook Islands (the)",
		"COL": "Colombia",
		"COM": "Comoros (the)",
		"CPV": "Cabo Verde",
		"CRI": "Costa Rica",
		"CUB": "Cuba",
		"CUW": "Curaçao",
		"CXR": "Christmas Island",
		"CYM": "Cayman Islands (the)",
		"CYP": "Cyprus",
		"CZE": "Czechia",
		"DEU": "Germany",
		"DJI": "Djibouti",
		"DMA": "Dominica",
		"DNK": "Denmark",
		"DOM": "Dominican Republic (the)",
		"DZA": "Algeria",
		"ECU": "Ecuador",
		"EGY": "Egypt",
		"ERI": "Eritrea",
		"ESH": "Western Sahara",
		"ESP": "Spain",
		"EST": "Estonia",
		"ETH": "Ethiopia",
		"FIN": "Finland",
		"FJI": "Fiji",
		"FLK": "Falkland Islands (the) [Malvinas]",
		"FRA": "France",
		"FRO": "Faroe Islands (the)",
		"FSM": "Micronesia (Federated States of)",
		"GAB": "Gabon",
		"GBR": "United Kingdom of Great Britain and Northern Ireland (the)",
		"GEO": "Georgia",
		"GGY": "Guernsey",
		"GHA": "Ghana",
		"GIB": "Gibraltar",
		"GIN": "Guinea",
		"GLP": "Guadeloupe",
		"GMB": "Gambia (the)",
		"GNB": "Guinea-Bissau",
		"GNQ": "Equatorial Guinea",
		"GRC": "Greece",
		"GRD": "Grenada",
		"GRL": "Greenland",
		"GTM": "Guatemala",
		"GUF": "French Guiana",
		"GUM": "Guam",
		"GUY": "Guyana",
		"HKG": "Hong Kong",
		"HMD": "Heard Island and McDonald Islands",
		"HND": "Honduras",
		"HRV": "Croatia",
		"HTI": "Haiti",
		"HUN": "Hungary",
		"IDN": "Indonesia",
		"IMN": "Isle of Man",
		"IND": "India",
		"IOT": "British Indian Ocean Territory (the)",
		"IRL": "Ireland",
		"IRN": "Iran (Islamic Republic of)",
		"IRQ": "Iraq",
		"ISL": "Iceland",
		"ISR": "Israel",
		"ITA": "Italy",
		"JAM": "Jamaica",
		"JEY": "Jersey",
		"JOR": "Jordan",
		"JPN": "Japan",
		"KAZ": "Kazakhstan",
		"KEN": "Kenya",
		"KGZ": "Kyrgyzstan",
		"KHM": "Cambodia",
		"KIR": "Kiribati",
		"KNA": "Saint Kitts and Nevis",
		"KOR": "Korea (the Republic of)",
		"KWT": "Kuwait",
		"LAO": "Lao People's Democratic Republic (the)",
		"LBN": "Lebanon",
		"LBR": "Liberia",
		"LBY": "Libya",
		"LCA": "Saint Lucia",
		"LIE": "Liechtenstein",
		"LKA": "Sri Lanka",
		"LSO": "Lesotho",
		"LTU": "Lithuania",
		"LUX": "Luxembourg",
		"LVA": "Latvia",
		"MAC": "Macao",
		"MAF": "Saint Martin (French part)",
		"MAR": "Morocco",
		"MCO": "Monaco",
		"MDA": "Moldova (the Republic of)",
		"MDG": "Madagascar",
		"MDV": "Maldives",
		"MEX": "Mexico",
		"MHL": "Marshall Islands (the)",
		"MKD": "Republic of North Macedonia",
		"MLI": "Mali",
		"MLT": "Malta",
		"MMR": "Myanmar",
		"MNE": "Montenegro",
		"MNG": "Mongolia",
		"MNP": "Northern Mariana Islands (the)",
		"MOZ": "Mozambique",
		"MRT": "Mauritania",
		"MSR": "Montserrat",
		"MTQ": "Martinique",
		"MUS": "Mauritius",
		"MWI": "Malawi",
		"MYS": "Malaysia",
		"MYT": "Mayotte",
		"NAM": "Namibia",
		"NCL": "New Caledonia",
		"NER": "Niger (the)",
		"NFK": "Norfolk Island",
		"NGA": "Nigeria",
		"NIC": "Nicaragua",
		"NIU": "Niue",
		"NLD": "Netherlands (the)",
		"NOR": "Norway",
		"NPL": "Nepal",
		"NRU": "Nauru",
		"NZL": "New Zealand",
		"OMN": "Oman",
		"PAK": "Pakistan",
		"PAN": "Panama",
		"PCN": "Pitcairn",
		"PER": "Peru",
		"PHL": "Philippines (the)",
		"PLW": "Palau",
		"PNG": "Papua New Guinea",
		"POL": "Poland",
		"PRI": "Puerto Rico",
		"PRK": "Korea (the Democratic People's Republic of)",
		"PRT": "Portugal",
		"PRY": "Paraguay",
		"PSE": "Palestine, State of",
		"PYF": "French Polynesia",
		"QAT": "Qatar",
		"REU": "Réunion",
		"ROU": "Romania",
		"RUS": "Russian Federation (the)",
		"RWA": "Rwanda",
		"SAU": "Saudi Arabia",
		"SDN": "Sudan (the)",
		"SEN": "Senegal",
		"SGP": "Singapore",
		"SGS": "South Georgia and the South Sandwich Islands",
		"SHN": "Saint Helena, Ascension and Tristan da Cunha",
		"SJM": "Svalbard and Jan Mayen",
		"SLB": "Solomon Islands",
		"SLE": "Sierra Leone",
		"SLV": "El Salvador",
		"SMR": "San Marino",
		"SOM": "Somalia",
		"SPM": "Saint Pierre and Miquelon",
		"SRB": "Serbia",
		"SSD": "South Sudan",
		"STP": "Sao Tome and Principe",
		"SUR": "Suriname",
		"SVK": "Slovakia",
		"SVN": "Slovenia",
		"SWE": "Sweden",
		"SWZ": "Eswatini",
		"SXM": "Sint Maarten (Dutch part)",
		"SYC": "Seychelles",
		"SYR": "Syrian Arab Republic",
		"TCA": "Turks and Caicos Islands (the)",
		"TCD": "Chad",
		"TGO": "Togo",
		"THA": "Thailand",
		"TJK": "Tajikistan",
		"TKL": "Tokelau",
		"TKM": "Turkmenistan",
		"TLS": "Timor-Leste",
		"TON": "Tonga",
		"TTO": "Trinidad and Tobago",
		"TUN": "Tunisia",
		"TUR": "Turkey",
		"TUV": "Tuvalu",
		"TWN": "Taiwan (Province of China)",
		"TZA": "Tanzania, United Republic of",
		"UGA": "Uganda",
		"UKR": "Ukraine",
		"UMI": "United States Minor Outlying Islands (the)",
		"URY": "Uruguay",
		"USA": "United States of America (the)",
		"UZB": "Uzbekistan",
		"VAT": "Holy See (the)",
		"VCT": "Saint Vincent and the Grenadines",
		"VEN": "Venezuela (Bolivarian Republic of)",
		"VGB": "Virgin Islands (British)",
		"VIR": "Virgin Islands (U.S.)",
		"VNM": "Viet Nam",
		"VUT": "Vanuatu",
		"WLF": "Wallis and Futuna",
		"WSM": "Samoa",
		"YEM": "Yemen",
		"ZAF": "South Africa",
		"ZMB": "Zambia",
		"ZWE": "Zimbabwe",
	}
}

func setTimeZoneCountryISOCodeMap() {
	timeZoneCountryISOCodeMap = map[string]string{
		"Asia/Kabul":                     "AFG",
		"Europe/Tirane":                  "ALB",
		"Africa/Algiers":                 "DZA",
		"Pacific/Pago_Pago":              "ASM",
		"Europe/Andorra":                 "AND",
		"Africa/Luanda":                  "AGO",
		"America/Anguilla":               "AIA",
		"Antarctica/Casey":               "ATA",
		"Antarctica/Davis":               "ATA",
		"Antarctica/DumontDUrville":      "ATA",
		"Antarctica/Mawson":              "ATA",
		"Antarctica/McMurdo":             "ATA",
		"Antarctica/Palmer":              "ATA",
		"Antarctica/Rothera":             "ATA",
		"Antarctica/Syowa":               "ATA",
		"Antarctica/Troll":               "ATA",
		"Antarctica/Vostok":              "ATA",
		"America/Antigua":                "ATG",
		"America/Argentina/Buenos_Aires": "ARG",
		"America/Argentina/Catamarca":    "ARG",
		"America/Argentina/Cordoba":      "ARG",
		"America/Argentina/Jujuy":        "ARG",
		"America/Argentina/La_Rioja":     "ARG",
		"America/Argentina/Mendoza":      "ARG",
		"America/Argentina/Rio_Gallegos": "ARG",
		"America/Argentina/Salta":        "ARG",
		"America/Argentina/San_Juan":     "ARG",
		"America/Argentina/San_Luis":     "ARG",
		"America/Argentina/Tucuman":      "ARG",
		"America/Argentina/Ushuaia":      "ARG",
		"Asia/Yerevan":                   "ARM",
		"America/Aruba":                  "ABW",
		"Antarctica/Macquarie":           "AUS",
		"Australia/Adelaide":             "AUS",
		"Australia/Brisbane":             "AUS",
		"Australia/Broken_Hill":          "AUS",
		"Australia/Darwin":               "AUS",
		"Australia/Eucla":                "AUS",
		"Australia/Hobart":               "AUS",
		"Australia/Lindeman":             "AUS",
		"Australia/Lord_Howe":            "AUS",
		"Australia/Melbourne":            "AUS",
		"Australia/Perth":                "AUS",
		"Australia/Sydney":               "AUS",
		"Europe/Vienna":                  "AUT",
		"Asia/Baku":                      "AZE",
		"America/Nassau":                 "BHS",
		"Asia/Bahrain":                   "BHR",
		"Asia/Dhaka":                     "BGD",
		"America/Barbados":               "BRB",
		"Europe/Minsk":                   "BLR",
		"Europe/Brussels":                "BEL",
		"America/Belize":                 "BLZ",
		"Africa/Porto-Novo":              "BEN",
		"Atlantic/Bermuda":               "BMU",
		"Asia/Thimphu":                   "BTN",
		"America/La_Paz":                 "BOL",
		"America/Kralendijk":             "BES",
		"Europe/Sarajevo":                "BIH",
		"Africa/Gaborone":                "BWA",
		"America/Araguaina":              "BRA",
		"America/Bahia":                  "BRA",
		"America/Belem":                  "BRA",
		"America/Boa_Vista":              "BRA",
		"America/Campo_Grande":           "BRA",
		"America/Cuiaba":                 "BRA",
		"America/Eirunepe":               "BRA",
		"America/Fortaleza":              "BRA",
		"America/Maceio":                 "BRA",
		"America/Manaus":                 "BRA",
		"America/Noronha":                "BRA",
		"America/Porto_Velho":            "BRA",
		"America/Recife":                 "BRA",
		"America/Rio_Branco":             "BRA",
		"America/Santarem":               "BRA",
		"America/Sao_Paulo":              "BRA",
		"Indian/Chagos":                  "IOT",
		"Asia/Brunei":                    "BRN",
		"Europe/Sofia":                   "BGR",
		"Africa/Ouagadougou":             "BFA",
		"Africa/Bujumbura":               "BDI",
		"Asia/Phnom_Penh":                "KHM",
		"Africa/Douala":                  "CMR",
		"America/Atikokan":               "CAN",
		"America/Blanc-Sablon":           "CAN",
		"America/Cambridge_Bay":          "CAN",
		"America/Creston":                "CAN",
		"America/Dawson":                 "CAN",
		"America/Dawson_Creek":           "CAN",
		"America/Edmonton":               "CAN",
		"America/Fort_Nelson":            "CAN",
		"America/Glace_Bay":              "CAN",
		"America/Goose_Bay":              "CAN",
		"America/Halifax":                "CAN",
		"America/Inuvik":                 "CAN",
		"America/Iqaluit":                "CAN",
		"America/Moncton":                "CAN",
		"America/Rankin_Inlet":           "CAN",
		"America/Regina":                 "CAN",
		"America/Resolute":               "CAN",
		"America/St_Johns":               "CAN",
		"America/Swift_Current":          "CAN",
		"America/Toronto":                "CAN",
		"America/Vancouver":              "CAN",
		"America/Whitehorse":             "CAN",
		"America/Winnipeg":               "CAN",
		"Atlantic/Cape_Verde":            "CPV",
		"America/Cayman":                 "CYM",
		"Africa/Bangui":                  "CAF",
		"Africa/Ndjamena":                "TCD",
		"America/Punta_Arenas":           "CHL",
		"America/Santiago":               "CHL",
		"Pacific/Easter":                 "CHL",
		"Asia/Shanghai":                  "CHN",
		"Asia/Urumqi":                    "CHN",
		"Indian/Christmas":               "CXR",
		"Indian/Cocos":                   "CCK",
		"America/Bogota":                 "COL",
		"Indian/Comoro":                  "COM",
		"Africa/Brazzaville":             "COG",
		"Africa/Kinshasa":                "COD",
		"Africa/Lubumbashi":              "COD",
		"Pacific/Rarotonga":              "COK",
		"America/Costa_Rica":             "CRI",
		"Europe/Zagreb":                  "HRV",
		"America/Havana":                 "CUB",
		"America/Curacao":                "CUW",
		"Asia/Famagusta":                 "CYP",
		"Asia/Nicosia":                   "CYP",
		"Europe/Prague":                  "CZE",
		"Africa/Abidjan":                 "CIV",
		"Europe/Copenhagen":              "DNK",
		"Africa/Djibouti":                "DJI",
		"America/Dominica":               "DMA",
		"America/Santo_Domingo":          "DOM",
		"America/Guayaquil":              "ECU",
		"Pacific/Galapagos":              "ECU",
		"Africa/Cairo":                   "EGY",
		"America/El_Salvador":            "SLV",
		"Africa/Malabo":                  "GNQ",
		"Africa/Asmara":                  "ERI",
		"Europe/Tallinn":                 "EST",
		"Africa/Addis_Ababa":             "ETH",
		"Atlantic/Stanley":               "FLK",
		"Atlantic/Faroe":                 "FRO",
		"Pacific/Fiji":                   "FJI",
		"Europe/Helsinki":                "FIN",
		"Europe/Paris":                   "FRA",
		"America/Cayenne":                "GUF",
		"Pacific/Gambier":                "PYF",
		"Pacific/Marquesas":              "PYF",
		"Pacific/Tahiti":                 "PYF",
		"Indian/Kerguelen":               "ATF",
		"Africa/Libreville":              "GAB",
		"Africa/Banjul":                  "GMB",
		"Asia/Tbilisi":                   "GEO",
		"Europe/Berlin":                  "DEU",
		"Europe/Busingen":                "DEU",
		"Africa/Accra":                   "GHA",
		"Europe/Gibraltar":               "GIB",
		"Europe/Athens":                  "GRC",
		"America/Danmarkshavn":           "GRL",
		"America/Nuuk":                   "GRL",
		"America/Scoresbysund":           "GRL",
		"America/Thule":                  "GRL",
		"America/Grenada":                "GRD",
		"America/Guadeloupe":             "GLP",
		"Pacific/Guam":                   "GUM",
		"America/Guatemala":              "GTM",
		"Europe/Guernsey":                "GGY",
		"Africa/Conakry":                 "GIN",
		"Africa/Bissau":                  "GNB",
		"America/Guyana":                 "GUY",
		"America/Port-au-Prince":         "HTI",
		"Europe/Vatican":                 "VAT",
		"America/Tegucigalpa":            "HND",
		"Asia/Hong_Kong":                 "HKG",
		"Europe/Budapest":                "HUN",
		"Atlantic/Reykjavik":             "ISL",
		"Asia/Kolkata":                   "IND",
		"Asia/Jakarta":                   "IDN",
		"Asia/Jayapura":                  "IDN",
		"Asia/Makassar":                  "IDN",
		"Asia/Pontianak":                 "IDN",
		"Asia/Tehran":                    "IRN",
		"Asia/Baghdad":                   "IRQ",
		"Europe/Dublin":                  "IRL",
		"Europe/Isle_of_Man":             "IMN",
		"Asia/Jerusalem":                 "ISR",
		"Europe/Rome":                    "ITA",
		"America/Jamaica":                "JAM",
		"Asia/Tokyo":                     "JPN",
		"Europe/Jersey":                  "JEY",
		"Asia/Amman":                     "JOR",
		"Asia/Almaty":                    "KAZ",
		"Asia/Aqtau":                     "KAZ",
		"Asia/Aqtobe":                    "KAZ",
		"Asia/Atyrau":                    "KAZ",
		"Asia/Oral":                      "KAZ",
		"Asia/Qostanay":                  "KAZ",
		"Asia/Qyzylorda":                 "KAZ",
		"Africa/Nairobi":                 "KEN",
		"Pacific/Kanton":                 "KIR",
		"Pacific/Kiritimati":             "KIR",
		"Pacific/Tarawa":                 "KIR",
		"Asia/Pyongyang":                 "PRK",
		"Asia/Seoul":                     "KOR",
		"Asia/Kuwait":                    "KWT",
		"Asia/Bishkek":                   "KGZ",
		"Asia/Vientiane":                 "LAO",
		"Europe/Riga":                    "LVA",
		"Asia/Beirut":                    "LBN",
		"Africa/Maseru":                  "LSO",
		"Africa/Monrovia":                "LBR",
		"Africa/Tripoli":                 "LBY",
		"Europe/Vaduz":                   "LIE",
		"Europe/Vilnius":                 "LTU",
		"Europe/Luxembourg":              "LUX",
		"Asia/Macau":                     "MAC",
		"Europe/Skopje":                  "MKD",
		"Indian/Antananarivo":            "MDG",
		"Africa/Blantyre":                "MWI",
		"Asia/Kuala_Lumpur":              "MYS",
		"Asia/Kuching":                   "MYS",
		"Indian/Maldives":                "MDV",
		"Africa/Bamako":                  "MLI",
		"Europe/Malta":                   "MLT",
		"Pacific/Kwajalein":              "MHL",
		"Pacific/Majuro":                 "MHL",
		"America/Martinique":             "MTQ",
		"Africa/Nouakchott":              "MRT",
		"Indian/Mauritius":               "MUS",
		"Indian/Mayotte":                 "MYT",
		"America/Bahia_Banderas":         "MEX",
		"America/Cancun":                 "MEX",
		"America/Chihuahua":              "MEX",
		"America/Ciudad_Juarez":          "MEX",
		"America/Hermosillo":             "MEX",
		"America/Matamoros":              "MEX",
		"America/Mazatlan":               "MEX",
		"America/Merida":                 "MEX",
		"America/Mexico_City":            "MEX",
		"America/Monterrey":              "MEX",
		"America/Ojinaga":                "MEX",
		"America/Tijuana":                "MEX",
		"Pacific/Chuuk":                  "FSM",
		"Pacific/Kosrae":                 "FSM",
		"Pacific/Pohnpei":                "FSM",
		"Europe/Chisinau":                "MDA",
		"Europe/Monaco":                  "MCO",
		"Asia/Hovd":                      "MNG",
		"Asia/Ulaanbaatar":               "MNG",
		"Europe/Podgorica":               "MNE",
		"America/Montserrat":             "MSR",
		"Africa/Casablanca":              "MAR",
		"Africa/El_Aaiun":                "MAR",
		"Africa/Maputo":                  "MOZ",
		"Asia/Yangon":                    "MMR",
		"Africa/Windhoek":                "NAM",
		"Pacific/Nauru":                  "NRU",
		"Asia/Kathmandu":                 "NPL",
		"Europe/Amsterdam":               "NLD",
		"Pacific/Noumea":                 "NCL",
		"Pacific/Auckland":               "NZL",
		"Pacific/Chatham":                "NZL",
		"America/Managua":                "NIC",
		"Africa/Niamey":                  "NER",
		"Africa/Lagos":                   "NGA",
		"Pacific/Niue":                   "NIU",
		"Pacific/Norfolk":                "NFK",
		"Pacific/Saipan":                 "MNP",
		"Europe/Oslo":                    "NOR",
		"Asia/Muscat":                    "OMN",
		"Asia/Karachi":                   "PAK",
		"Pacific/Palau":                  "PLW",
		"Asia/Gaza":                      "PSE",
		"Asia/Hebron":                    "PSE",
		"America/Panama":                 "PAN",
		"Pacific/Bougainville":           "PNG",
		"Pacific/Port_Moresby":           "PNG",
		"America/Asuncion":               "PRY",
		"America/Lima":                   "PER",
		"Asia/Manila":                    "PHL",
		"Pacific/Pitcairn":               "PCN",
		"Europe/Warsaw":                  "POL",
		"Atlantic/Azores":                "PRT",
		"Atlantic/Madeira":               "PRT",
		"Europe/Lisbon":                  "PRT",
		"America/Puerto_Rico":            "PRI",
		"Asia/Qatar":                     "QAT",
		"Europe/Bucharest":               "ROU",
		"Asia/Anadyr":                    "RUS",
		"Asia/Barnaul":                   "RUS",
		"Asia/Chita":                     "RUS",
		"Asia/Irkutsk":                   "RUS",
		"Asia/Kamchatka":                 "RUS",
		"Asia/Khandyga":                  "RUS",
		"Asia/Krasnoyarsk":               "RUS",
		"Asia/Magadan":                   "RUS",
		"Asia/Novokuznetsk":              "RUS",
		"Asia/Novosibirsk":               "RUS",
		"Asia/Omsk":                      "RUS",
		"Asia/Sakhalin":                  "RUS",
		"Asia/Srednekolymsk":             "RUS",
		"Asia/Tomsk":                     "RUS",
		"Asia/Ust-Nera":                  "RUS",
		"Asia/Vladivostok":               "RUS",
		"Asia/Yakutsk":                   "RUS",
		"Asia/Yekaterinburg":             "RUS",
		"Europe/Astrakhan":               "RUS",
		"Europe/Kaliningrad":             "RUS",
		"Europe/Kirov":                   "RUS",
		"Europe/Moscow":                  "RUS",
		"Europe/Samara":                  "RUS",
		"Europe/Saratov":                 "RUS",
		"Europe/Ulyanovsk":               "RUS",
		"Europe/Volgograd":               "RUS",
		"Africa/Kigali":                  "RWA",
		"Indian/Reunion":                 "REU",
		"America/St_Barthelemy":          "BLM",
		"Atlantic/St_Helena":             "SHN",
		"America/St_Kitts":               "KNA",
		"America/St_Lucia":               "LCA",
		"America/Marigot":                "MAF",
		"America/Miquelon":               "SPM",
		"America/St_Vincent":             "VCT",
		"Pacific/Apia":                   "WSM",
		"Europe/San_Marino":              "SMR",
		"Africa/Sao_Tome":                "STP",
		"Asia/Riyadh":                    "SAU",
		"Africa/Dakar":                   "SEN",
		"Europe/Belgrade":                "SRB",
		"Indian/Mahe":                    "SYC",
		"Africa/Freetown":                "SLE",
		"Asia/Singapore":                 "SGP",
		"America/Lower_Princes":          "SXM",
		"Europe/Bratislava":              "SVK",
		"Europe/Ljubljana":               "SVN",
		"Pacific/Guadalcanal":            "SLB",
		"Africa/Mogadishu":               "SOM",
		"Africa/Johannesburg":            "ZAF",
		"Atlantic/South_Georgia":         "SGS",
		"Africa/Juba":                    "SSD",
		"Africa/Ceuta":                   "ESP",
		"Atlantic/Canary":                "ESP",
		"Europe/Madrid":                  "ESP",
		"Asia/Colombo":                   "LKA",
		"Africa/Khartoum":                "SDN",
		"America/Paramaribo":             "SUR",
		"Arctic/Longyearbyen":            "SJM",
		"Africa/Mbabane":                 "SWZ",
		"Europe/Stockholm":               "SWE",
		"Europe/Zurich":                  "CHE",
		"Asia/Damascus":                  "SYR",
		"Asia/Taipei":                    "TWN",
		"Asia/Dushanbe":                  "TJK",
		"Africa/Dar_es_Salaam":           "TZA",
		"Asia/Bangkok":                   "THA",
		"Asia/Dili":                      "TLS",
		"Africa/Lome":                    "TGO",
		"Pacific/Fakaofo":                "TKL",
		"Pacific/Tongatapu":              "TON",
		"America/Port_of_Spain":          "TTO",
		"Africa/Tunis":                   "TUN",
		"Europe/Istanbul":                "TUR",
		"Asia/Ashgabat":                  "TKM",
		"America/Grand_Turk":             "TCA",
		"Pacific/Funafuti":               "TUV",
		"Africa/Kampala":                 "UGA",
		"Europe/Kyiv":                    "UKR",
		"Europe/Simferopol":              "UKR",
		"Asia/Dubai":                     "ARE",
		"Europe/London":                  "GBR",
		"America/Adak":                   "USA",
		"America/Anchorage":              "USA",
		"America/Boise":                  "USA",
		"America/Chicago":                "USA",
		"America/Denver":                 "USA",
		"America/Detroit":                "USA",
		"America/Indiana/Indianapolis":   "USA",
		"America/Indiana/Knox":           "USA",
		"America/Indiana/Marengo":        "USA",
		"America/Indiana/Petersburg":     "USA",
		"America/Indiana/Tell_City":      "USA",
		"America/Indiana/Vevay":          "USA",
		"America/Indiana/Vincennes":      "USA",
		"America/Indiana/Winamac":        "USA",
		"America/Juneau":                 "USA",
		"America/Kentucky/Louisville":    "USA",
		"America/Kentucky/Monticello":    "USA",
		"America/Los_Angeles":            "USA",
		"America/Menominee":              "USA",
		"America/Metlakatla":             "USA",
		"America/New_York":               "USA",
		"America/Nome":                   "USA",
		"America/North_Dakota/Beulah":    "USA",
		"America/North_Dakota/Center":    "USA",
		"America/North_Dakota/New_Salem": "USA",
		"America/Phoenix":                "USA",
		"America/Sitka":                  "USA",
		"America/Yakutat":                "USA",
		"Pacific/Honolulu":               "USA",
		"Pacific/Midway":                 "UMI",
		"Pacific/Wake":                   "UMI",
		"America/Montevideo":             "URY",
		"Asia/Samarkand":                 "UZB",
		"Asia/Tashkent":                  "UZB",
		"Pacific/Efate":                  "VUT",
		"America/Caracas":                "VEN",
		"Asia/Ho_Chi_Minh":               "VNM",
		"America/Tortola":                "VGB",
		"America/St_Thomas":              "VIR",
		"Pacific/Wallis":                 "WLF",
		"Asia/Aden":                      "YEM",
		"Africa/Lusaka":                  "ZMB",
		"Africa/Harare":                  "ZWE",
		"Europe/Mariehamn":               "ALA",
	}
}

var setCountryISOCodeNameMapOnce = sync.OnceFunc(setCountryISOCodeNameMap)

var setTimeZoneCountryISOCodeMapOnce = sync.OnceFunc(setTimeZoneCountryISOCodeMap)
