package country

type Country struct {
	IsoCode string
	Name    string
}

type TimeZone struct {
	CountryIsoCode string
	Name           string
}

var Countries = []Country{
	{IsoCode: "AND", Name: "Andorra"},
	{IsoCode: "ARE", Name: "United Arab Emirates"},
	{IsoCode: "AFG", Name: "Afghanistan"},
	{IsoCode: "ATG", Name: "Antigua and Barbuda"},
	{IsoCode: "AIA", Name: "Anguilla"},
	{IsoCode: "ALB", Name: "Albania"},
	{IsoCode: "ARM", Name: "Armenia"},
	{IsoCode: "AGO", Name: "Angola"},
	{IsoCode: "ATA", Name: "Antarctica"},
	{IsoCode: "ARG", Name: "Argentina"},
	{IsoCode: "ASM", Name: "American Samoa"},
	{IsoCode: "AUT", Name: "Austria"},
	{IsoCode: "STP", Name: "Sao Tome and Principe"},
	{IsoCode: "SLV", Name: "El Salvador"},
	{IsoCode: "SXM", Name: "Sint Maarten"},
	{IsoCode: "SYR", Name: "Syria"},
	{IsoCode: "SWZ", Name: "Eswatini"},
	{IsoCode: "TCA", Name: "Turks and Caicos Islands"},
	{IsoCode: "TCD", Name: "Chad"},
	{IsoCode: "ATF", Name: "French Southern Territories"},
	{IsoCode: "LIE", Name: "Liechtenstein"},
	{IsoCode: "LKA", Name: "Sri Lanka"},
	{IsoCode: "LBR", Name: "Liberia"},
	{IsoCode: "LSO", Name: "Lesotho"},
	{IsoCode: "LTU", Name: "Lithuania"},
	{IsoCode: "LUX", Name: "Luxembourg"},
	{IsoCode: "LVA", Name: "Latvia"},
	{IsoCode: "LBY", Name: "Libya"},
	{IsoCode: "MAR", Name: "Morocco"},
	{IsoCode: "MCO", Name: "Monaco"},
	{IsoCode: "MDA", Name: "Moldova"},
	{IsoCode: "MNE", Name: "Montenegro"},
	{IsoCode: "MAF", Name: "Saint Martin"},
	{IsoCode: "MDG", Name: "Madagascar"},
	{IsoCode: "MHL", Name: "Marshall Islands"},
	{IsoCode: "MKD", Name: "North Macedonia"},
	{IsoCode: "MLI", Name: "Mali"},
	{IsoCode: "MMR", Name: "Myanmar"},
	{IsoCode: "MNG", Name: "Mongolia"},
	{IsoCode: "MAC", Name: "Macao"},
	{IsoCode: "MNP", Name: "Northern Mariana Islands"},
	{IsoCode: "MTQ", Name: "Martinique"},
	{IsoCode: "MRT", Name: "Mauritania"},
	{IsoCode: "MSR", Name: "Montserrat"},
	{IsoCode: "MLT", Name: "Malta"},
	{IsoCode: "MUS", Name: "Mauritius"},
	{IsoCode: "MDV", Name: "Maldives"},
	{IsoCode: "MWI", Name: "Malawi"},
	{IsoCode: "MEX", Name: "Mexico"},
	{IsoCode: "MYS", Name: "Malaysia"},
	{IsoCode: "MOZ", Name: "Mozambique"},
	{IsoCode: "NAM", Name: "Namibia"},
	{IsoCode: "NCL", Name: "New Caledonia"},
	{IsoCode: "NER", Name: "Niger"},
	{IsoCode: "NFK", Name: "Norfolk Island"},
	{IsoCode: "NGA", Name: "Nigeria"},
	{IsoCode: "NIC", Name: "Nicaragua"},
	{IsoCode: "NLD", Name: "Netherlands"},
	{IsoCode: "NOR", Name: "Norway"},
	{IsoCode: "NPL", Name: "Nepal"},
	{IsoCode: "NRU", Name: "Nauru"},
	{IsoCode: "NIU", Name: "Niue"},
	{IsoCode: "NZL", Name: "New Zealand"},
	{IsoCode: "OMN", Name: "Oman"},
	{IsoCode: "PAN", Name: "Panama"},
	{IsoCode: "PER", Name: "Peru"},
	{IsoCode: "PYF", Name: "French Polynesia"},
	{IsoCode: "PNG", Name: "Papua New Guinea"},
	{IsoCode: "PHL", Name: "Philippines"},
	{IsoCode: "PAK", Name: "Pakistan"},
	{IsoCode: "POL", Name: "Poland"},
	{IsoCode: "SPM", Name: "Saint Pierre and Miquelon"},
	{IsoCode: "PCN", Name: "Pitcairn"},
	{IsoCode: "BLM", Name: "Saint Barthelemy"},
	{IsoCode: "BMU", Name: "Bermuda"},
	{IsoCode: "BRN", Name: "Brunei"},
	{IsoCode: "BOL", Name: "Bolivia"},
	{IsoCode: "BES", Name: "Bonaire, Saint Eustatius and Saba"},
	{IsoCode: "BRA", Name: "Brazil"},
	{IsoCode: "BHS", Name: "Bahamas"},
	{IsoCode: "BTN", Name: "Bhutan"},
	{IsoCode: "BWA", Name: "Botswana"},
	{IsoCode: "BLR", Name: "Belarus"},
	{IsoCode: "BLZ", Name: "Belize"},
	{IsoCode: "CAN", Name: "Canada"},
	{IsoCode: "CCK", Name: "Cocos Islands"},
	{IsoCode: "COD", Name: "Democratic Republic of the Congo"},
	{IsoCode: "CAF", Name: "Central African Republic"},
	{IsoCode: "COG", Name: "Republic of the Congo"},
	{IsoCode: "CHE", Name: "Switzerland"},
	{IsoCode: "CIV", Name: "Ivory Coast"},
	{IsoCode: "COK", Name: "Cook Islands"},
	{IsoCode: "CHL", Name: "Chile"},
	{IsoCode: "CMR", Name: "Cameroon"},
	{IsoCode: "CHN", Name: "China"},
	{IsoCode: "COL", Name: "Colombia"},
	{IsoCode: "CRI", Name: "Costa Rica"},
	{IsoCode: "CUB", Name: "Cuba"},
	{IsoCode: "CPV", Name: "Cabo Verde"},
	{IsoCode: "CUW", Name: "Curacao"},
	{IsoCode: "CXR", Name: "Christmas Island"},
	{IsoCode: "CYP", Name: "Cyprus"},
	{IsoCode: "CZE", Name: "Czechia"},
	{IsoCode: "DEU", Name: "Germany"},
	{IsoCode: "DJI", Name: "Djibouti"},
	{IsoCode: "DNK", Name: "Denmark"},
	{IsoCode: "FRO", Name: "Faroe Islands"},
	{IsoCode: "FRA", Name: "France"},
	{IsoCode: "GAB", Name: "Gabon"},
	{IsoCode: "GBR", Name: "United Kingdom"},
	{IsoCode: "GRD", Name: "Grenada"},
	{IsoCode: "GEO", Name: "Georgia"},
	{IsoCode: "GUF", Name: "French Guiana"},
	{IsoCode: "GGY", Name: "Guernsey"},
	{IsoCode: "GHA", Name: "Ghana"},
	{IsoCode: "GIB", Name: "Gibraltar"},
	{IsoCode: "GRL", Name: "Greenland"},
	{IsoCode: "GMB", Name: "Gambia"},
	{IsoCode: "GIN", Name: "Guinea"},
	{IsoCode: "GLP", Name: "Guadeloupe"},
	{IsoCode: "GNQ", Name: "Equatorial Guinea"},
	{IsoCode: "GRC", Name: "Greece"},
	{IsoCode: "SGS", Name: "South Georgia and the South Sandwich Islands"},
	{IsoCode: "GTM", Name: "Guatemala"},
	{IsoCode: "GUM", Name: "Guam"},
	{IsoCode: "GNB", Name: "Guinea-Bissau"},
	{IsoCode: "GUY", Name: "Guyana"},
	{IsoCode: "HKG", Name: "Hong Kong"},
	{IsoCode: "HND", Name: "Honduras"},
	{IsoCode: "HRV", Name: "Croatia"},
	{IsoCode: "HTI", Name: "Haiti"},
	{IsoCode: "HUN", Name: "Hungary"},
	{IsoCode: "IDN", Name: "Indonesia"},
	{IsoCode: "IRL", Name: "Ireland"},
	{IsoCode: "ISR", Name: "Israel"},
	{IsoCode: "IMN", Name: "Isle of Man"},
	{IsoCode: "IND", Name: "India"},
	{IsoCode: "IOT", Name: "British Indian Ocean Territory"},
	{IsoCode: "IRQ", Name: "Iraq"},
	{IsoCode: "DMA", Name: "Dominica"},
	{IsoCode: "DOM", Name: "Dominican Republic"},
	{IsoCode: "DZA", Name: "Algeria"},
	{IsoCode: "ECU", Name: "Ecuador"},
	{IsoCode: "EST", Name: "Estonia"},
	{IsoCode: "EGY", Name: "Egypt"},
	{IsoCode: "ESH", Name: "Western Sahara"},
	{IsoCode: "ERI", Name: "Eritrea"},
	{IsoCode: "ESP", Name: "Spain"},
	{IsoCode: "ETH", Name: "Ethiopia"},
	{IsoCode: "FIN", Name: "Finland"},
	{IsoCode: "FJI", Name: "Fiji"},
	{IsoCode: "FLK", Name: "Falkland Islands"},
	{IsoCode: "FSM", Name: "Micronesia"},
	{IsoCode: "IRN", Name: "Iran"},
	{IsoCode: "ISL", Name: "Iceland"},
	{IsoCode: "ITA", Name: "Italy"},
	{IsoCode: "JEY", Name: "Jersey"},
	{IsoCode: "JAM", Name: "Jamaica"},
	{IsoCode: "JOR", Name: "Jordan"},
	{IsoCode: "JPN", Name: "Japan"},
	{IsoCode: "AUS", Name: "Australia"},
	{IsoCode: "ABW", Name: "Aruba"},
	{IsoCode: "ALA", Name: "Aland Islands"},
	{IsoCode: "AZE", Name: "Azerbaijan"},
	{IsoCode: "BIH", Name: "Bosnia and Herzegovina"},
	{IsoCode: "BRB", Name: "Barbados"},
	{IsoCode: "BGD", Name: "Bangladesh"},
	{IsoCode: "BEL", Name: "Belgium"},
	{IsoCode: "BFA", Name: "Burkina Faso"},
	{IsoCode: "BGR", Name: "Bulgaria"},
	{IsoCode: "BHR", Name: "Bahrain"},
	{IsoCode: "BDI", Name: "Burundi"},
	{IsoCode: "BEN", Name: "Benin"},
	{IsoCode: "KEN", Name: "Kenya"},
	{IsoCode: "KGZ", Name: "Kyrgyzstan"},
	{IsoCode: "KHM", Name: "Cambodia"},
	{IsoCode: "KIR", Name: "Kiribati"},
	{IsoCode: "COM", Name: "Comoros"},
	{IsoCode: "KNA", Name: "Saint Kitts and Nevis"},
	{IsoCode: "PRK", Name: "North Korea"},
	{IsoCode: "KOR", Name: "South Korea"},
	{IsoCode: "KWT", Name: "Kuwait"},
	{IsoCode: "CYM", Name: "Cayman Islands"},
	{IsoCode: "KAZ", Name: "Kazakhstan"},
	{IsoCode: "LAO", Name: "Laos"},
	{IsoCode: "LBN", Name: "Lebanon"},
	{IsoCode: "LCA", Name: "Saint Lucia"},
	{IsoCode: "PRI", Name: "Puerto Rico"},
	{IsoCode: "PSE", Name: "Palestinian Territory"},
	{IsoCode: "PRT", Name: "Portugal"},
	{IsoCode: "PLW", Name: "Palau"},
	{IsoCode: "PRY", Name: "Paraguay"},
	{IsoCode: "QAT", Name: "Qatar"},
	{IsoCode: "REU", Name: "Reunion"},
	{IsoCode: "ROU", Name: "Romania"},
	{IsoCode: "SRB", Name: "Serbia"},
	{IsoCode: "RUS", Name: "Russia"},
	{IsoCode: "RWA", Name: "Rwanda"},
	{IsoCode: "SAU", Name: "Saudi Arabia"},
	{IsoCode: "SLB", Name: "Solomon Islands"},
	{IsoCode: "SYC", Name: "Seychelles"},
	{IsoCode: "SDN", Name: "Sudan"},
	{IsoCode: "SWE", Name: "Sweden"},
	{IsoCode: "SGP", Name: "Singapore"},
	{IsoCode: "SHN", Name: "Saint Helena"},
	{IsoCode: "SVN", Name: "Slovenia"},
	{IsoCode: "SJM", Name: "Svalbard and Jan Mayen"},
	{IsoCode: "SVK", Name: "Slovakia"},
	{IsoCode: "SLE", Name: "Sierra Leone"},
	{IsoCode: "SMR", Name: "San Marino"},
	{IsoCode: "SEN", Name: "Senegal"},
	{IsoCode: "SOM", Name: "Somalia"},
	{IsoCode: "SUR", Name: "Suriname"},
	{IsoCode: "SSD", Name: "South Sudan"},
	{IsoCode: "TGO", Name: "Togo"},
	{IsoCode: "THA", Name: "Thailand"},
	{IsoCode: "TJK", Name: "Tajikistan"},
	{IsoCode: "TKL", Name: "Tokelau"},
	{IsoCode: "TLS", Name: "Timor Leste"},
	{IsoCode: "TKM", Name: "Turkmenistan"},
	{IsoCode: "TUN", Name: "Tunisia"},
	{IsoCode: "TON", Name: "Tonga"},
	{IsoCode: "TUR", Name: "Turkey"},
	{IsoCode: "TTO", Name: "Trinidad and Tobago"},
	{IsoCode: "TUV", Name: "Tuvalu"},
	{IsoCode: "TWN", Name: "Taiwan"},
	{IsoCode: "TZA", Name: "Tanzania"},
	{IsoCode: "UKR", Name: "Ukraine"},
	{IsoCode: "UGA", Name: "Uganda"},
	{IsoCode: "UMI", Name: "United States Minor Outlying Islands"},
	{IsoCode: "USA", Name: "United States"},
	{IsoCode: "URY", Name: "Uruguay"},
	{IsoCode: "UZB", Name: "Uzbekistan"},
	{IsoCode: "VAT", Name: "Vatican"},
	{IsoCode: "VCT", Name: "Saint Vincent and the Grenadines"},
	{IsoCode: "VEN", Name: "Venezuela"},
	{IsoCode: "VGB", Name: "British Virgin Islands"},
	{IsoCode: "VIR", Name: "U.S. Virgin Islands"},
	{IsoCode: "VNM", Name: "Vietnam"},
	{IsoCode: "VUT", Name: "Vanuatu"},
	{IsoCode: "WLF", Name: "Wallis and Futuna"},
	{IsoCode: "WSM", Name: "Samoa"},
	{IsoCode: "YEM", Name: "Yemen"},
	{IsoCode: "MYT", Name: "Mayotte"},
	{IsoCode: "ZAF", Name: "South Africa"},
	{IsoCode: "ZMB", Name: "Zambia"},
	{IsoCode: "ZWE", Name: "Zimbabwe"},
}

var TimeZones = []TimeZone{
	{CountryIsoCode: "CIV", Name: "Africa/Abidjan"},
	{CountryIsoCode: "GHA", Name: "Africa/Accra"},
	{CountryIsoCode: "ETH", Name: "Africa/Addis_Ababa"},
	{CountryIsoCode: "DZA", Name: "Africa/Algiers"},
	{CountryIsoCode: "ERI", Name: "Africa/Asmara"},
	{CountryIsoCode: "MLI", Name: "Africa/Bamako"},
	{CountryIsoCode: "CAF", Name: "Africa/Bangui"},
	{CountryIsoCode: "GMB", Name: "Africa/Banjul"},
	{CountryIsoCode: "GNB", Name: "Africa/Bissau"},
	{CountryIsoCode: "MWI", Name: "Africa/Blantyre"},
	{CountryIsoCode: "COG", Name: "Africa/Brazzaville"},
	{CountryIsoCode: "BDI", Name: "Africa/Bujumbura"},
	{CountryIsoCode: "EGY", Name: "Africa/Cairo"},
	{CountryIsoCode: "MAR", Name: "Africa/Casablanca"},
	{CountryIsoCode: "ESP", Name: "Africa/Ceuta"},
	{CountryIsoCode: "GIN", Name: "Africa/Conakry"},
	{CountryIsoCode: "SEN", Name: "Africa/Dakar"},
	{CountryIsoCode: "TZA", Name: "Africa/Dar_es_Salaam"},
	{CountryIsoCode: "DJI", Name: "Africa/Djibouti"},
	{CountryIsoCode: "CMR", Name: "Africa/Douala"},
	{CountryIsoCode: "ESH", Name: "Africa/El_Aaiun"},
	{CountryIsoCode: "SLE", Name: "Africa/Freetown"},
	{CountryIsoCode: "BWA", Name: "Africa/Gaborone"},
	{CountryIsoCode: "ZWE", Name: "Africa/Harare"},
	{CountryIsoCode: "ZAF", Name: "Africa/Johannesburg"},
	{CountryIsoCode: "SSD", Name: "Africa/Juba"},
	{CountryIsoCode: "UGA", Name: "Africa/Kampala"},
	{CountryIsoCode: "SDN", Name: "Africa/Khartoum"},
	{CountryIsoCode: "RWA", Name: "Africa/Kigali"},
	{CountryIsoCode: "COD", Name: "Africa/Kinshasa"},
	{CountryIsoCode: "NGA", Name: "Africa/Lagos"},
	{CountryIsoCode: "GAB", Name: "Africa/Libreville"},
	{CountryIsoCode: "TGO", Name: "Africa/Lome"},
	{CountryIsoCode: "AGO", Name: "Africa/Luanda"},
	{CountryIsoCode: "COD", Name: "Africa/Lubumbashi"},
	{CountryIsoCode: "ZMB", Name: "Africa/Lusaka"},
	{CountryIsoCode: "GNQ", Name: "Africa/Malabo"},
	{CountryIsoCode: "MOZ", Name: "Africa/Maputo"},
	{CountryIsoCode: "LSO", Name: "Africa/Maseru"},
	{CountryIsoCode: "SWZ", Name: "Africa/Mbabane"},
	{CountryIsoCode: "SOM", Name: "Africa/Mogadishu"},
	{CountryIsoCode: "LBR", Name: "Africa/Monrovia"},
	{CountryIsoCode: "KEN", Name: "Africa/Nairobi"},
	{CountryIsoCode: "TCD", Name: "Africa/Ndjamena"},
	{CountryIsoCode: "NER", Name: "Africa/Niamey"},
	{CountryIsoCode: "MRT", Name: "Africa/Nouakchott"},
	{CountryIsoCode: "BFA", Name: "Africa/Ouagadougou"},
	{CountryIsoCode: "BEN", Name: "Africa/Porto-Novo"},
	{CountryIsoCode: "STP", Name: "Africa/Sao_Tome"},
	{CountryIsoCode: "LBY", Name: "Africa/Tripoli"},
	{CountryIsoCode: "TUN", Name: "Africa/Tunis"},
	{CountryIsoCode: "NAM", Name: "Africa/Windhoek"},
	{CountryIsoCode: "USA", Name: "America/Adak"},
	{CountryIsoCode: "USA", Name: "America/Anchorage"},
	{CountryIsoCode: "AIA", Name: "America/Anguilla"},
	{CountryIsoCode: "ATG", Name: "America/Antigua"},
	{CountryIsoCode: "BRA", Name: "America/Araguaina"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/Buenos_Aires"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/Catamarca"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/Cordoba"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/Jujuy"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/La_Rioja"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/Mendoza"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/Rio_Gallegos"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/Salta"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/San_Juan"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/San_Luis"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/Tucuman"},
	{CountryIsoCode: "ARG", Name: "America/Argentina/Ushuaia"},
	{CountryIsoCode: "ABW", Name: "America/Aruba"},
	{CountryIsoCode: "PRY", Name: "America/Asuncion"},
	{CountryIsoCode: "CAN", Name: "America/Atikokan"},
	{CountryIsoCode: "BRA", Name: "America/Bahia"},
	{CountryIsoCode: "MEX", Name: "America/Bahia_Banderas"},
	{CountryIsoCode: "BRB", Name: "America/Barbados"},
	{CountryIsoCode: "BRA", Name: "America/Belem"},
	{CountryIsoCode: "BLZ", Name: "America/Belize"},
	{CountryIsoCode: "CAN", Name: "America/Blanc-Sablon"},
	{CountryIsoCode: "BRA", Name: "America/Boa_Vista"},
	{CountryIsoCode: "COL", Name: "America/Bogota"},
	{CountryIsoCode: "USA", Name: "America/Boise"},
	{CountryIsoCode: "ARG", Name: "America/Buenos_Aires"},
	{CountryIsoCode: "CAN", Name: "America/Cambridge_Bay"},
	{CountryIsoCode: "BRA", Name: "America/Campo_Grande"},
	{CountryIsoCode: "MEX", Name: "America/Cancun"},
	{CountryIsoCode: "VEN", Name: "America/Caracas"},
	{CountryIsoCode: "GUF", Name: "America/Cayenne"},
	{CountryIsoCode: "CYM", Name: "America/Cayman"},
	{CountryIsoCode: "USA", Name: "America/Chicago"},
	{CountryIsoCode: "MEX", Name: "America/Chihuahua"},
	{CountryIsoCode: "CRI", Name: "America/Costa_Rica"},
	{CountryIsoCode: "CAN", Name: "America/Creston"},
	{CountryIsoCode: "BRA", Name: "America/Cuiaba"},
	{CountryIsoCode: "CUW", Name: "America/Curacao"},
	{CountryIsoCode: "GRL", Name: "America/Danmarkshavn"},
	{CountryIsoCode: "CAN", Name: "America/Dawson"},
	{CountryIsoCode: "CAN", Name: "America/Dawson_Creek"},
	{CountryIsoCode: "USA", Name: "America/Denver"},
	{CountryIsoCode: "USA", Name: "America/Detroit"},
	{CountryIsoCode: "DMA", Name: "America/Dominica"},
	{CountryIsoCode: "CAN", Name: "America/Edmonton"},
	{CountryIsoCode: "BRA", Name: "America/Eirunepe"},
	{CountryIsoCode: "SLV", Name: "America/El_Salvador"},
	{CountryIsoCode: "CAN", Name: "America/Fort_Nelson"},
	{CountryIsoCode: "BRA", Name: "America/Fortaleza"},
	{CountryIsoCode: "CAN", Name: "America/Glace_Bay"},
	{CountryIsoCode: "CAN", Name: "America/Goose_Bay"},
	{CountryIsoCode: "TCA", Name: "America/Grand_Turk"},
	{CountryIsoCode: "GRD", Name: "America/Grenada"},
	{CountryIsoCode: "GLP", Name: "America/Guadeloupe"},
	{CountryIsoCode: "GTM", Name: "America/Guatemala"},
	{CountryIsoCode: "ECU", Name: "America/Guayaquil"},
	{CountryIsoCode: "GUY", Name: "America/Guyana"},
	{CountryIsoCode: "CAN", Name: "America/Halifax"},
	{CountryIsoCode: "CUB", Name: "America/Havana"},
	{CountryIsoCode: "MEX", Name: "America/Hermosillo"},
	{CountryIsoCode: "USA", Name: "America/Indiana/Indianapolis"},
	{CountryIsoCode: "USA", Name: "America/Indiana/Knox"},
	{CountryIsoCode: "USA", Name: "America/Indiana/Marengo"},
	{CountryIsoCode: "USA", Name: "America/Indiana/Petersburg"},
	{CountryIsoCode: "USA", Name: "America/Indiana/Tell_City"},
	{CountryIsoCode: "USA", Name: "America/Indiana/Vevay"},
	{CountryIsoCode: "USA", Name: "America/Indiana/Vincennes"},
	{CountryIsoCode: "USA", Name: "America/Indiana/Winamac"},
	{CountryIsoCode: "USA", Name: "America/Indianapolis"},
	{CountryIsoCode: "CAN", Name: "America/Inuvik"},
	{CountryIsoCode: "CAN", Name: "America/Iqaluit"},
	{CountryIsoCode: "JAM", Name: "America/Jamaica"},
	{CountryIsoCode: "USA", Name: "America/Juneau"},
	{CountryIsoCode: "USA", Name: "America/Kentucky/Louisville"},
	{CountryIsoCode: "USA", Name: "America/Kentucky/Monticello"},
	{CountryIsoCode: "BES", Name: "America/Kralendijk"},
	{CountryIsoCode: "BOL", Name: "America/La_Paz"},
	{CountryIsoCode: "PER", Name: "America/Lima"},
	{CountryIsoCode: "USA", Name: "America/Los_Angeles"},
	{CountryIsoCode: "SXM", Name: "America/Lower_Princes"},
	{CountryIsoCode: "BRA", Name: "America/Maceio"},
	{CountryIsoCode: "NIC", Name: "America/Managua"},
	{CountryIsoCode: "BRA", Name: "America/Manaus"},
	{CountryIsoCode: "MAF", Name: "America/Marigot"},
	{CountryIsoCode: "MTQ", Name: "America/Martinique"},
	{CountryIsoCode: "MEX", Name: "America/Matamoros"},
	{CountryIsoCode: "MEX", Name: "America/Mazatlan"},
	{CountryIsoCode: "USA", Name: "America/Menominee"},
	{CountryIsoCode: "MEX", Name: "America/Merida"},
	{CountryIsoCode: "USA", Name: "America/Metlakatla"},
	{CountryIsoCode: "MEX", Name: "America/Mexico_City"},
	{CountryIsoCode: "SPM", Name: "America/Miquelon"},
	{CountryIsoCode: "CAN", Name: "America/Moncton"},
	{CountryIsoCode: "MEX", Name: "America/Monterrey"},
	{CountryIsoCode: "URY", Name: "America/Montevideo"},
	{CountryIsoCode: "MSR", Name: "America/Montserrat"},
	{CountryIsoCode: "BHS", Name: "America/Nassau"},
	{CountryIsoCode: "USA", Name: "America/New_York"},
	{CountryIsoCode: "CAN", Name: "America/Nipigon"},
	{CountryIsoCode: "USA", Name: "America/Nome"},
	{CountryIsoCode: "BRA", Name: "America/Noronha"},
	{CountryIsoCode: "USA", Name: "America/North_Dakota/Beulah"},
	{CountryIsoCode: "USA", Name: "America/North_Dakota/Center"},
	{CountryIsoCode: "USA", Name: "America/North_Dakota/New_Salem"},
	{CountryIsoCode: "GRL", Name: "America/Nuuk"},
	{CountryIsoCode: "MEX", Name: "America/Ojinaga"},
	{CountryIsoCode: "PAN", Name: "America/Panama"},
	{CountryIsoCode: "CAN", Name: "America/Pangnirtung"},
	{CountryIsoCode: "SUR", Name: "America/Paramaribo"},
	{CountryIsoCode: "USA", Name: "America/Phoenix"},
	{CountryIsoCode: "TTO", Name: "America/Port_of_Spain"},
	{CountryIsoCode: "HTI", Name: "America/Port-au-Prince"},
	{CountryIsoCode: "BRA", Name: "America/Porto_Velho"},
	{CountryIsoCode: "PRI", Name: "America/Puerto_Rico"},
	{CountryIsoCode: "CHL", Name: "America/Punta_Arenas"},
	{CountryIsoCode: "CAN", Name: "America/Rainy_River"},
	{CountryIsoCode: "CAN", Name: "America/Rankin_Inlet"},
	{CountryIsoCode: "BRA", Name: "America/Recife"},
	{CountryIsoCode: "CAN", Name: "America/Regina"},
	{CountryIsoCode: "CAN", Name: "America/Resolute"},
	{CountryIsoCode: "BRA", Name: "America/Rio_Branco"},
	{CountryIsoCode: "BRA", Name: "America/Santarem"},
	{CountryIsoCode: "CHL", Name: "America/Santiago"},
	{CountryIsoCode: "DOM", Name: "America/Santo_Domingo"},
	{CountryIsoCode: "BRA", Name: "America/Sao_Paulo"},
	{CountryIsoCode: "GRL", Name: "America/Scoresbysund"},
	{CountryIsoCode: "USA", Name: "America/Sitka"},
	{CountryIsoCode: "BLM", Name: "America/St_Barthelemy"},
	{CountryIsoCode: "CAN", Name: "America/St_Johns"},
	{CountryIsoCode: "KNA", Name: "America/St_Kitts"},
	{CountryIsoCode: "LCA", Name: "America/St_Lucia"},
	{CountryIsoCode: "VIR", Name: "America/St_Thomas"},
	{CountryIsoCode: "VCT", Name: "America/St_Vincent"},
	{CountryIsoCode: "CAN", Name: "America/Swift_Current"},
	{CountryIsoCode: "HND", Name: "America/Tegucigalpa"},
	{CountryIsoCode: "GRL", Name: "America/Thule"},
	{CountryIsoCode: "CAN", Name: "America/Thunder_Bay"},
	{CountryIsoCode: "MEX", Name: "America/Tijuana"},
	{CountryIsoCode: "CAN", Name: "America/Toronto"},
	{CountryIsoCode: "VGB", Name: "America/Tortola"},
	{CountryIsoCode: "CAN", Name: "America/Vancouver"},
	{CountryIsoCode: "CAN", Name: "America/Whitehorse"},
	{CountryIsoCode: "CAN", Name: "America/Winnipeg"},
	{CountryIsoCode: "USA", Name: "America/Yakutat"},
	{CountryIsoCode: "CAN", Name: "America/Yellowknife"},
	{CountryIsoCode: "ATA", Name: "Antarctica/Casey"},
	{CountryIsoCode: "ATA", Name: "Antarctica/Davis"},
	{CountryIsoCode: "ATA", Name: "Antarctica/DumontDUrville"},
	{CountryIsoCode: "AUS", Name: "Antarctica/Macquarie"},
	{CountryIsoCode: "ATA", Name: "Antarctica/Mawson"},
	{CountryIsoCode: "ATA", Name: "Antarctica/McMurdo"},
	{CountryIsoCode: "ATA", Name: "Antarctica/Palmer"},
	{CountryIsoCode: "ATA", Name: "Antarctica/Rothera"},
	{CountryIsoCode: "ATA", Name: "Antarctica/Syowa"},
	{CountryIsoCode: "ATA", Name: "Antarctica/Troll"},
	{CountryIsoCode: "ATA", Name: "Antarctica/Vostok"},
	{CountryIsoCode: "SJM", Name: "Arctic/Longyearbyen"},
	{CountryIsoCode: "YEM", Name: "Asia/Aden"},
	{CountryIsoCode: "KAZ", Name: "Asia/Almaty"},
	{CountryIsoCode: "JOR", Name: "Asia/Amman"},
	{CountryIsoCode: "RUS", Name: "Asia/Anadyr"},
	{CountryIsoCode: "KAZ", Name: "Asia/Aqtau"},
	{CountryIsoCode: "KAZ", Name: "Asia/Aqtobe"},
	{CountryIsoCode: "TKM", Name: "Asia/Ashgabat"},
	{CountryIsoCode: "KAZ", Name: "Asia/Atyrau"},
	{CountryIsoCode: "IRQ", Name: "Asia/Baghdad"},
	{CountryIsoCode: "BHR", Name: "Asia/Bahrain"},
	{CountryIsoCode: "AZE", Name: "Asia/Baku"},
	{CountryIsoCode: "THA", Name: "Asia/Bangkok"},
	{CountryIsoCode: "RUS", Name: "Asia/Barnaul"},
	{CountryIsoCode: "LBN", Name: "Asia/Beirut"},
	{CountryIsoCode: "KGZ", Name: "Asia/Bishkek"},
	{CountryIsoCode: "BRN", Name: "Asia/Brunei"},
	{CountryIsoCode: "IND", Name: "Asia/Calcutta"},
	{CountryIsoCode: "RUS", Name: "Asia/Chita"},
	{CountryIsoCode: "MNG", Name: "Asia/Choibalsan"},
	{CountryIsoCode: "LKA", Name: "Asia/Colombo"},
	{CountryIsoCode: "SYR", Name: "Asia/Damascus"},
	{CountryIsoCode: "BGD", Name: "Asia/Dhaka"},
	{CountryIsoCode: "TLS", Name: "Asia/Dili"},
	{CountryIsoCode: "ARE", Name: "Asia/Dubai"},
	{CountryIsoCode: "TJK", Name: "Asia/Dushanbe"},
	{CountryIsoCode: "CYP", Name: "Asia/Famagusta"},
	{CountryIsoCode: "PSE", Name: "Asia/Gaza"},
	{CountryIsoCode: "PSE", Name: "Asia/Hebron"},
	{CountryIsoCode: "VNM", Name: "Asia/Ho_Chi_Minh"},
	{CountryIsoCode: "HKG", Name: "Asia/Hong_Kong"},
	{CountryIsoCode: "MNG", Name: "Asia/Hovd"},
	{CountryIsoCode: "RUS", Name: "Asia/Irkutsk"},
	{CountryIsoCode: "TUR", Name: "Asia/Istanbul"},
	{CountryIsoCode: "IDN", Name: "Asia/Jakarta"},
	{CountryIsoCode: "IDN", Name: "Asia/Jayapura"},
	{CountryIsoCode: "ISR", Name: "Asia/Jerusalem"},
	{CountryIsoCode: "AFG", Name: "Asia/Kabul"},
	{CountryIsoCode: "RUS", Name: "Asia/Kamchatka"},
	{CountryIsoCode: "PAK", Name: "Asia/Karachi"},
	{CountryIsoCode: "NPL", Name: "Asia/Kathmandu"},
	{CountryIsoCode: "RUS", Name: "Asia/Khandyga"},
	{CountryIsoCode: "IND", Name: "Asia/Kolkata"},
	{CountryIsoCode: "RUS", Name: "Asia/Krasnoyarsk"},
	{CountryIsoCode: "MYS", Name: "Asia/Kuala_Lumpur"},
	{CountryIsoCode: "MYS", Name: "Asia/Kuching"},
	{CountryIsoCode: "KWT", Name: "Asia/Kuwait"},
	{CountryIsoCode: "MAC", Name: "Asia/Macau"},
	{CountryIsoCode: "RUS", Name: "Asia/Magadan"},
	{CountryIsoCode: "IDN", Name: "Asia/Makassar"},
	{CountryIsoCode: "PHL", Name: "Asia/Manila"},
	{CountryIsoCode: "OMN", Name: "Asia/Muscat"},
	{CountryIsoCode: "CYP", Name: "Asia/Nicosia"},
	{CountryIsoCode: "RUS", Name: "Asia/Novokuznetsk"},
	{CountryIsoCode: "RUS", Name: "Asia/Novosibirsk"},
	{CountryIsoCode: "RUS", Name: "Asia/Omsk"},
	{CountryIsoCode: "KAZ", Name: "Asia/Oral"},
	{CountryIsoCode: "KHM", Name: "Asia/Phnom_Penh"},
	{CountryIsoCode: "IDN", Name: "Asia/Pontianak"},
	{CountryIsoCode: "PRK", Name: "Asia/Pyongyang"},
	{CountryIsoCode: "QAT", Name: "Asia/Qatar"},
	{CountryIsoCode: "KAZ", Name: "Asia/Qostanay"},
	{CountryIsoCode: "KAZ", Name: "Asia/Qyzylorda"},
	{CountryIsoCode: "SAU", Name: "Asia/Riyadh"},
	{CountryIsoCode: "VNM", Name: "Asia/Saigon"},
	{CountryIsoCode: "RUS", Name: "Asia/Sakhalin"},
	{CountryIsoCode: "UZB", Name: "Asia/Samarkand"},
	{CountryIsoCode: "KOR", Name: "Asia/Seoul"},
	{CountryIsoCode: "CHN", Name: "Asia/Shanghai"},
	{CountryIsoCode: "SGP", Name: "Asia/Singapore"},
	{CountryIsoCode: "RUS", Name: "Asia/Srednekolymsk"},
	{CountryIsoCode: "TWN", Name: "Asia/Taipei"},
	{CountryIsoCode: "UZB", Name: "Asia/Tashkent"},
	{CountryIsoCode: "GEO", Name: "Asia/Tbilisi"},
	{CountryIsoCode: "IRN", Name: "Asia/Tehran"},
	{CountryIsoCode: "BTN", Name: "Asia/Thimphu"},
	{CountryIsoCode: "JPN", Name: "Asia/Tokyo"},
	{CountryIsoCode: "RUS", Name: "Asia/Tomsk"},
	{CountryIsoCode: "MNG", Name: "Asia/Ulaanbaatar"},
	{CountryIsoCode: "CHN", Name: "Asia/Urumqi"},
	{CountryIsoCode: "RUS", Name: "Asia/Ust-Nera"},
	{CountryIsoCode: "LAO", Name: "Asia/Vientiane"},
	{CountryIsoCode: "RUS", Name: "Asia/Vladivostok"},
	{CountryIsoCode: "RUS", Name: "Asia/Yakutsk"},
	{CountryIsoCode: "MMR", Name: "Asia/Yangon"},
	{CountryIsoCode: "RUS", Name: "Asia/Yekaterinburg"},
	{CountryIsoCode: "ARM", Name: "Asia/Yerevan"},
	{CountryIsoCode: "PRT", Name: "Atlantic/Azores"},
	{CountryIsoCode: "BMU", Name: "Atlantic/Bermuda"},
	{CountryIsoCode: "ESP", Name: "Atlantic/Canary"},
	{CountryIsoCode: "CPV", Name: "Atlantic/Cape_Verde"},
	{CountryIsoCode: "FRO", Name: "Atlantic/Faroe"},
	{CountryIsoCode: "PRT", Name: "Atlantic/Madeira"},
	{CountryIsoCode: "ISL", Name: "Atlantic/Reykjavik"},
	{CountryIsoCode: "SGS", Name: "Atlantic/South_Georgia"},
	{CountryIsoCode: "SHN", Name: "Atlantic/St_Helena"},
	{CountryIsoCode: "FLK", Name: "Atlantic/Stanley"},
	{CountryIsoCode: "AUS", Name: "Australia/Adelaide"},
	{CountryIsoCode: "AUS", Name: "Australia/Brisbane"},
	{CountryIsoCode: "AUS", Name: "Australia/Broken_Hill"},
	{CountryIsoCode: "AUS", Name: "Australia/Darwin"},
	{CountryIsoCode: "AUS", Name: "Australia/Eucla"},
	{CountryIsoCode: "AUS", Name: "Australia/Hobart"},
	{CountryIsoCode: "AUS", Name: "Australia/Lindeman"},
	{CountryIsoCode: "AUS", Name: "Australia/Lord_Howe"},
	{CountryIsoCode: "AUS", Name: "Australia/Melbourne"},
	{CountryIsoCode: "AUS", Name: "Australia/Perth"},
	{CountryIsoCode: "AUS", Name: "Australia/Sydney"},
	{CountryIsoCode: "NLD", Name: "Europe/Amsterdam"},
	{CountryIsoCode: "AND", Name: "Europe/Andorra"},
	{CountryIsoCode: "RUS", Name: "Europe/Astrakhan"},
	{CountryIsoCode: "GRC", Name: "Europe/Athens"},
	{CountryIsoCode: "SRB", Name: "Europe/Belgrade"},
	{CountryIsoCode: "DEU", Name: "Europe/Berlin"},
	{CountryIsoCode: "SVK", Name: "Europe/Bratislava"},
	{CountryIsoCode: "BEL", Name: "Europe/Brussels"},
	{CountryIsoCode: "ROU", Name: "Europe/Bucharest"},
	{CountryIsoCode: "HUN", Name: "Europe/Budapest"},
	{CountryIsoCode: "DEU", Name: "Europe/Busingen"},
	{CountryIsoCode: "MDA", Name: "Europe/Chisinau"},
	{CountryIsoCode: "DNK", Name: "Europe/Copenhagen"},
	{CountryIsoCode: "IRL", Name: "Europe/Dublin"},
	{CountryIsoCode: "GIB", Name: "Europe/Gibraltar"},
	{CountryIsoCode: "GGY", Name: "Europe/Guernsey"},
	{CountryIsoCode: "FIN", Name: "Europe/Helsinki"},
	{CountryIsoCode: "IMN", Name: "Europe/Isle_of_Man"},
	{CountryIsoCode: "TUR", Name: "Europe/Istanbul"},
	{CountryIsoCode: "JEY", Name: "Europe/Jersey"},
	{CountryIsoCode: "RUS", Name: "Europe/Kaliningrad"},
	{CountryIsoCode: "UKR", Name: "Europe/Kiev"},
	{CountryIsoCode: "RUS", Name: "Europe/Kirov"},
	{CountryIsoCode: "PRT", Name: "Europe/Lisbon"},
	{CountryIsoCode: "SVN", Name: "Europe/Ljubljana"},
	{CountryIsoCode: "GBR", Name: "Europe/London"},
	{CountryIsoCode: "LUX", Name: "Europe/Luxembourg"},
	{CountryIsoCode: "ESP", Name: "Europe/Madrid"},
	{CountryIsoCode: "MLT", Name: "Europe/Malta"},
	{CountryIsoCode: "ALA", Name: "Europe/Mariehamn"},
	{CountryIsoCode: "BLR", Name: "Europe/Minsk"},
	{CountryIsoCode: "MCO", Name: "Europe/Monaco"},
	{CountryIsoCode: "RUS", Name: "Europe/Moscow"},
	{CountryIsoCode: "CYP", Name: "Europe/Nicosia"},
	{CountryIsoCode: "NOR", Name: "Europe/Oslo"},
	{CountryIsoCode: "FRA", Name: "Europe/Paris"},
	{CountryIsoCode: "MNE", Name: "Europe/Podgorica"},
	{CountryIsoCode: "CZE", Name: "Europe/Prague"},
	{CountryIsoCode: "LVA", Name: "Europe/Riga"},
	{CountryIsoCode: "ITA", Name: "Europe/Rome"},
	{CountryIsoCode: "RUS", Name: "Europe/Samara"},
	{CountryIsoCode: "SMR", Name: "Europe/San_Marino"},
	{CountryIsoCode: "BIH", Name: "Europe/Sarajevo"},
	{CountryIsoCode: "RUS", Name: "Europe/Saratov"},
	{CountryIsoCode: "UKR", Name: "Europe/Simferopol"},
	{CountryIsoCode: "MKD", Name: "Europe/Skopje"},
	{CountryIsoCode: "BGR", Name: "Europe/Sofia"},
	{CountryIsoCode: "SWE", Name: "Europe/Stockholm"},
	{CountryIsoCode: "EST", Name: "Europe/Tallinn"},
	{CountryIsoCode: "ALB", Name: "Europe/Tirane"},
	{CountryIsoCode: "RUS", Name: "Europe/Ulyanovsk"},
	{CountryIsoCode: "UKR", Name: "Europe/Uzhgorod"},
	{CountryIsoCode: "LIE", Name: "Europe/Vaduz"},
	{CountryIsoCode: "VAT", Name: "Europe/Vatican"},
	{CountryIsoCode: "AUT", Name: "Europe/Vienna"},
	{CountryIsoCode: "LTU", Name: "Europe/Vilnius"},
	{CountryIsoCode: "RUS", Name: "Europe/Volgograd"},
	{CountryIsoCode: "POL", Name: "Europe/Warsaw"},
	{CountryIsoCode: "HRV", Name: "Europe/Zagreb"},
	{CountryIsoCode: "UKR", Name: "Europe/Zaporozhye"},
	{CountryIsoCode: "CHE", Name: "Europe/Zurich"},
	{CountryIsoCode: "MDG", Name: "Indian/Antananarivo"},
	{CountryIsoCode: "IOT", Name: "Indian/Chagos"},
	{CountryIsoCode: "CXR", Name: "Indian/Christmas"},
	{CountryIsoCode: "CCK", Name: "Indian/Cocos"},
	{CountryIsoCode: "COM", Name: "Indian/Comoro"},
	{CountryIsoCode: "ATF", Name: "Indian/Kerguelen"},
	{CountryIsoCode: "SYC", Name: "Indian/Mahe"},
	{CountryIsoCode: "MDV", Name: "Indian/Maldives"},
	{CountryIsoCode: "MUS", Name: "Indian/Mauritius"},
	{CountryIsoCode: "MYT", Name: "Indian/Mayotte"},
	{CountryIsoCode: "REU", Name: "Indian/Reunion"},
	{CountryIsoCode: "WSM", Name: "Pacific/Apia"},
	{CountryIsoCode: "NZL", Name: "Pacific/Auckland"},
	{CountryIsoCode: "PNG", Name: "Pacific/Bougainville"},
	{CountryIsoCode: "NZL", Name: "Pacific/Chatham"},
	{CountryIsoCode: "FSM", Name: "Pacific/Chuuk"},
	{CountryIsoCode: "CHL", Name: "Pacific/Easter"},
	{CountryIsoCode: "VUT", Name: "Pacific/Efate"},
	{CountryIsoCode: "KIR", Name: "Pacific/Enderbury"},
	{CountryIsoCode: "TKL", Name: "Pacific/Fakaofo"},
	{CountryIsoCode: "FJI", Name: "Pacific/Fiji"},
	{CountryIsoCode: "TUV", Name: "Pacific/Funafuti"},
	{CountryIsoCode: "ECU", Name: "Pacific/Galapagos"},
	{CountryIsoCode: "PYF", Name: "Pacific/Gambier"},
	{CountryIsoCode: "SLB", Name: "Pacific/Guadalcanal"},
	{CountryIsoCode: "GUM", Name: "Pacific/Guam"},
	{CountryIsoCode: "USA", Name: "Pacific/Honolulu"},
	{CountryIsoCode: "KIR", Name: "Pacific/Kiritimati"},
	{CountryIsoCode: "FSM", Name: "Pacific/Kosrae"},
	{CountryIsoCode: "MHL", Name: "Pacific/Kwajalein"},
	{CountryIsoCode: "MHL", Name: "Pacific/Majuro"},
	{CountryIsoCode: "PYF", Name: "Pacific/Marquesas"},
	{CountryIsoCode: "UMI", Name: "Pacific/Midway"},
	{CountryIsoCode: "NRU", Name: "Pacific/Nauru"},
	{CountryIsoCode: "NIU", Name: "Pacific/Niue"},
	{CountryIsoCode: "NFK", Name: "Pacific/Norfolk"},
	{CountryIsoCode: "NCL", Name: "Pacific/Noumea"},
	{CountryIsoCode: "ASM", Name: "Pacific/Pago_Pago"},
	{CountryIsoCode: "PLW", Name: "Pacific/Palau"},
	{CountryIsoCode: "PCN", Name: "Pacific/Pitcairn"},
	{CountryIsoCode: "FSM", Name: "Pacific/Pohnpei"},
	{CountryIsoCode: "PNG", Name: "Pacific/Port_Moresby"},
	{CountryIsoCode: "COK", Name: "Pacific/Rarotonga"},
	{CountryIsoCode: "MNP", Name: "Pacific/Saipan"},
	{CountryIsoCode: "PYF", Name: "Pacific/Tahiti"},
	{CountryIsoCode: "KIR", Name: "Pacific/Tarawa"},
	{CountryIsoCode: "TON", Name: "Pacific/Tongatapu"},
	{CountryIsoCode: "UMI", Name: "Pacific/Wake"},
	{CountryIsoCode: "WLF", Name: "Pacific/Wallis"},
}

var IsoCodeMap = map[string]Country{}
var TimeZoneNameCountryIsoCodeMap = map[string]string{}

func init() {
	for _, country := range Countries {
		IsoCodeMap[country.IsoCode] = country
	}

	for _, timeZone := range TimeZones {
		country := IsoCodeMap[timeZone.CountryIsoCode]
		if country.Name != "" {
			TimeZoneNameCountryIsoCodeMap[timeZone.Name] = country.IsoCode
		}
	}
}

func GetNameFromIsoCode(isoCode string) string {
	return IsoCodeMap[isoCode].Name
}

func GetIsoCodeFromTimeZoneName(timeZoneName string) *string {
	countryIsoCode := TimeZoneNameCountryIsoCodeMap[timeZoneName]
	if countryIsoCode == "" {
		return nil
	}

	return &countryIsoCode
}
