# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/refs/heads/main/pipeline/frontend/yaml/linter/schema/schema.json
services:
- environment:
    DOCKER_TLS_CERTDIR: /dind-certs
  image: docker:dind
  name: docker
  ports:
  - 2376
  - 32768
  - 32769
  privileged: true

steps:
- commands:
  - golangci-lint run --timeout 10m
  depends_on: []
  directory: backend
  image: golangci/golangci-lint
  name: backend-lint

- commands:
  - go test ./...
  depends_on: []
  directory: backend
  environment:
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_TLS_VERIFY: "0"
  image: golang:1.24.3
  name: backend-tests

- commands:
  - npm install -g pnpm
  - pnpm install
  - pnpm exec -- tsc
  - pnpm exec -- eslint .
  - pnpm exec -- stylelint "src/**/*.scss"
  depends_on: []
  directory: frontend
  image: node:24
  name: frontend

- commands:
  - |
    SUM1=$(sha256sum MANIFESTO.md | awk '{print $1}')
    SUM2=$(sha256sum frontend/src/components/Manifesto/manifesto.md | awk '{print $1}')
    if [ "$SUM1" != "$SUM2" ]; then
      echo "Manifesto file has changed, please update the frontend/src/components/Manifesto/manifesto.md file."
      exit 1
    fi
  image: alpine:3
  name: check-manifesto

when:
- event: pull_request
