# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/refs/heads/main/pipeline/frontend/yaml/linter/schema/schema.json
skip_clone: true

steps:

  - commands:
      - git clone https://$${CODEBERG_USER}:$${CODEBERG_TOKEN}@codeberg.org/${CI_REPO_OWNER}/poeticmetric-infrastructure.git infrastructure
    environment:
      CODEBERG_TOKEN:
        from_secret: CODEBERG_TOKEN
      CODEBERG_USER:
        from_secret: CODEBERG_USER
    image: alpine/git
    name: clone-infrastructure

  - commands:
      - touch environment-secrets
      - |
        for V in \
          CLICKHOUSE_PASSWORD \
          GOOGLE_CLIENT_ID \
          GOOGLE_CLIENT_SECRET \
          KUBERNETES_NAMESPACE \
          POSTGRES_PASSWORD \
          RABBITMQ_PASSWORD \
          STRIPE_PUBLISHABLE_KEY \
          STRIPE_SECRET_KEY \
          STRIPE_WEBHOOK_SIGNING_SECRET \
          VALKEY_PASSWORD; do
            VAR_NAME="${CI_PIPELINE_DEPLOY_TARGET^^}_$${V}"
            eval "echo \"$${V}=\$${$${VAR_NAME}}\"" >> environment-secrets
        done
    environment:
      # production
#      CLICKHOUSE_PASSWORD:
#        from_secret: CLICKHOUSE_PASSWORD
#      GOOGLE_CLIENT_ID:
#        from_secret: GOOGLE_CLIENT_ID
#      GOOGLE_CLIENT_SECRET:
#        from_secret: GOOGLE_CLIENT_SECRET
#      KUBERNETES_NAMESPACE:
#        from_secret: KUBERNETES_NAMESPACE
#      POSTGRES_PASSWORD:
#        from_secret: POSTGRES_PASSWORD
#      RABBITMQ_PASSWORD:
#        from_secret: RABBITMQ_PASSWORD
#      STRIPE_PUBLISHABLE_KEY:
#        from_secret: STRIPE_PUBLISHABLE_KEY
#      STRIPE_SECRET_KEY:
#        from_secret: STRIPE_SECRET_KEY
#      STRIPE_WEBHOOK_SIGNING_SECRET:
#        from_secret: STRIPE_WEBHOOK_SIGNING_SECRET
#      VALKEY_PASSWORD:
#        from_secret: VALKEY_PASSWORD
      # staging
      STAGING_CLICKHOUSE_PASSWORD:
        from_secret: STAGING_CLICKHOUSE_PASSWORD
      STAGING_GOOGLE_CLIENT_ID:
        from_secret: STAGING_GOOGLE_CLIENT_ID
      STAGING_GOOGLE_CLIENT_SECRET:
        from_secret: STAGING_GOOGLE_CLIENT_SECRET
      STAGING_KUBERNETES_NAMESPACE:
        from_secret: STAGING_KUBERNETES_NAMESPACE
      STAGING_POSTGRES_PASSWORD:
        from_secret: STAGING_POSTGRES_PASSWORD
      STAGING_RABBITMQ_PASSWORD:
        from_secret: STAGING_RABBITMQ_PASSWORD
      STAGING_STRIPE_PUBLISHABLE_KEY:
        from_secret: STAGING_STRIPE_PUBLISHABLE_KEY
      STAGING_STRIPE_SECRET_KEY:
        from_secret: STAGING_STRIPE_SECRET_KEY
      STAGING_STRIPE_WEBHOOK_SIGNING_SECRET:
        from_secret: STAGING_STRIPE_WEBHOOK_SIGNING_SECRET
      STAGING_VALKEY_PASSWORD:
        from_secret: STAGING_VALKEY_PASSWORD
    image: alpine
    name: prepare-environment-secrets

  - commands:
      - source environment-secrets
      - mkdir ~/.kube
      - echo $${KUBE_CONFIG} | base64 -d > ~/.kube/config
      - chmod 400 ~/.kube/config
      - |
        if [ -n "$${RESET}" ]; then
          kubectl --namespace "$${KUBERNETES_NAMESPACE}" rollout restart statefulsets
          sleep 4
        fi
      - |
        helm upgrade poeticmetric poeticmetric \
          --install \
          --namespace "$${KUBERNETES_NAMESPACE}" \
          --repo https://codeberg.org/api/packages/${CI_REPO_OWNER}/helm \
          --set clickhouse.password="$${CLICKHOUSE_PASSWORD}" \
          --set poeticmetric.backend.image.tag="${CI_COMMIT_TAG##v}" \
          --set poeticmetric.config.google.clientID="$${GOOGLE_CLIENT_ID}" \
          --set poeticmetric.config.google.clientSecret="$${GOOGLE_CLIENT_SECRET}" \
          --set poeticmetric.config.smtp.password="$${SMTP_PASSWORD}" \
          --set poeticmetric.config.smtp.user="$${SMTP_USER}" \
          --set poeticmetric.config.registryAuth.host="codeberg.org" \
          --set poeticmetric.config.registryAuth.password="$${REGISTRY_PASSWORD}" \
          --set poeticmetric.config.registryAuth.user="$${REGISTRY_USER}" \
          --set poeticmetric.config.stripe.publishableKey="$${STRIPE_PUBLISHABLE_KEY}" \
          --set poeticmetric.config.stripe.secretKey="$${STRIPE_SECRET_KEY}" \
          --set poeticmetric.config.stripe.webhookSigningSecret="$${STRIPE_WEBHOOK_SIGNING_SECRET}" \
          --set poeticmetric.frontend.image.tag="${CI_COMMIT_TAG##v}" \
          --set postgres.password="$${POSTGRES_PASSWORD}" \
          --set rabbitmq.password="$${RABBITMQ_PASSWORD}" \
          --set valkey.password="$${VALKEY_PASSWORD}" \
          --values "infrastructure/etc/${CI_PIPELINE_DEPLOY_TARGET}/values.yaml" \
          --version "${CI_COMMIT_TAG##v}"
    depends_on:
      - clone-infrastructure
      - prepare-environment-secrets
    environment:
      KUBE_CONFIG:
        from_secret: KUBE_CONFIG
      SMTP_PASSWORD:
        from_secret: SMTP_PASSWORD
      SMTP_USER:
        from_secret: SMTP_USER
    image: alpine/k8s:1.33.1
    name: install-helm-chart

when:
  - evaluate: "CI_PIPELINE_DEPLOY_TARGET in ['production', 'staging']"
    event: deployment
