# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/refs/heads/main/pipeline/frontend/yaml/linter/schema/schema.json
steps:

- depends_on: []
  directory: backend
  image: woodpeckerci/plugin-docker-buildx
  name: build-backend-image
  settings:
    password:
      from_secret: CODEBERG_TOKEN
    platforms: linux/amd64
    registry: codeberg.org
    repo: codeberg.org/${CI_REPO}/backend
    tag: ${CI_COMMIT_TAG##v}
    username:
      from_secret: CODEBERG_USER

- depends_on: []
  directory: frontend
  image: woodpeckerci/plugin-docker-buildx
  name: build-frontend-image
  settings:
    password:
      from_secret: CODEBERG_TOKEN
    platforms: linux/amd64
    registry: codeberg.org
    repo: codeberg.org/${CI_REPO}/frontend
    tag: ${CI_COMMIT_TAG##v}
    username:
      from_secret: CODEBERG_USER

- commands:
  - helm package chart --app-version ${CI_COMMIT_TAG##v} --version ${CI_COMMIT_TAG##v}
  - |
    curl \
    --user ${CODEBERG_USER}:${CODEBERG_TOKEN} \
    -X POST \
    --upload-file ./${CI_REPO_NAME}-${CI_COMMIT_TAG##v}.tgz \
    https://codeberg.org/api/packages/${CI_REPO_OWNER}/helm/api/charts
  depends_on: []
  environment:
    CODEBERG_TOKEN:
      from_secret: CODEBERG_TOKEN
    CODEBERG_USER:
      from_secret: CODEBERG_USER
  image: alpine/helm
  name: build-helm-chart

- depends_on:
  - build-backend-image
  - build-frontend-image
  - build-helm-chart
  image: woodpeckerci/plugin-release
  name: release
  settings:
    api_key:
      from_secret: CODEBERG_TOKEN
    title: ${CI_COMMIT_TAG}

when:
- event: tag
