# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/refs/heads/main/pipeline/frontend/yaml/linter/schema/schema.json
steps:

  - backend_options:
      kubernetes:
        resources:
          requests:
            cpu: 2
            memory: 2Gi
    commands:
      - /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock > /dev/null 2>&1 &
      - while ! docker version > /dev/null 2>&1; do :; done
      - echo "$${FORGEJO_TOKEN}" | docker login --password-stdin --username $${FORGEJO_USER} code.unius.sh > /dev/null 2>&1
      - /usr/local/bin/docker buildx create --name builder --use > /dev/null 2>&1
      - |
        /usr/local/bin/docker buildx build \
          --build-arg GO_BUILD_ARGS="-p 2" \
          --cache-from "access_key_id=$${HETZNER_ACCESS_KEY},bucket=unius-cache,endpoint_url=nbg1.your-objectstorage.com,secret_access_key=$${HETZNER_SECRET_KEY},type=s3" \
          --cache-to "access_key_id=$${HETZNER_ACCESS_KEY},bucket=unius-cache,endpoint_url=nbg1.your-objectstorage.com,mode=max,type=s3,secret_access_key=$${HETZNER_SECRET_KEY}" \
          --file "Dockerfile" \
          --output "type=image,push=true,rewrite-timestamp=true" \
          --platform "linux/amd64" \
          --pull \
          --tag "code.unius.sh/unius/poeticmetric-backend:${CI_COMMIT_TAG##v}" \
          .
    depends_on: []
    directory: backend
    environment:
      HETZNER_ACCESS_KEY:
        from_secret: HETZNER_ACCESS_KEY
      HETZNER_SECRET_KEY:
        from_secret: HETZNER_SECRET_KEY
      FORGEJO_TOKEN:
        from_secret: FORGEJO_TOKEN
      FORGEJO_USER:
        from_secret: FORGEJO_USER
    image: woodpeckerci/plugin-docker-buildx
    name: build-backend-image
    privileged: true

  - backend_options:
      kubernetes:
        resources:
          requests:
            cpu: 2
            memory: 2Gi
    commands:
      - /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock > /dev/null 2>&1 &
      - while ! docker version > /dev/null 2>&1; do :; done
      - echo "$${FORGEJO_TOKEN}" | docker login --password-stdin --username $${FORGEJO_USER} code.unius.sh > /dev/null 2>&1
      - /usr/local/bin/docker buildx create --name builder --use > /dev/null 2>&1
      - |
        /usr/local/bin/docker buildx build \
          --cache-from "access_key_id=$${HETZNER_ACCESS_KEY},bucket=unius-cache,endpoint_url=nbg1.your-objectstorage.com,secret_access_key=$${HETZNER_SECRET_KEY},type=s3" \
          --cache-to "access_key_id=$${HETZNER_ACCESS_KEY},bucket=unius-cache,endpoint_url=nbg1.your-objectstorage.com,mode=max,type=s3,secret_access_key=$${HETZNER_SECRET_KEY}" \
          --file "Dockerfile" \
          --output "type=image,push=true,rewrite-timestamp=true" \
          --platform "linux/amd64" \
          --pull \
          --tag "code.unius.sh/unius/poeticmetric-frontend:${CI_COMMIT_TAG##v}" \
          .
    depends_on: []
    directory: frontend
    environment:
      HETZNER_ACCESS_KEY:
        from_secret: HETZNER_ACCESS_KEY
      HETZNER_SECRET_KEY:
        from_secret: HETZNER_SECRET_KEY
      FORGEJO_TOKEN:
        from_secret: FORGEJO_TOKEN
      FORGEJO_USER:
        from_secret: FORGEJO_USER
    image: woodpeckerci/plugin-docker-buildx
    name: build-frontend-image
    privileged: true

  - backend_options:
      kubernetes:
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
    commands:
      - helm package chart --app-version ${CI_COMMIT_TAG##v} --version ${CI_COMMIT_TAG##v}
      - |
        curl \
        --user $${FORGEJO_USER}:$${FORGEJO_TOKEN} \
        -X POST \
        --upload-file ./${CI_REPO_NAME}-${CI_COMMIT_TAG##v}.tgz \
        https://code.unius.sh/api/packages/unius/helm/api/charts
    depends_on: []
    environment:
      FORGEJO_TOKEN:
        from_secret: FORGEJO_TOKEN
      FORGEJO_USER:
        from_secret: FORGEJO_USER
    image: alpine/helm
    name: build-helm-chart

  - depends_on:
      - build-backend-image
      - build-frontend-image
      - build-helm-chart
    image: woodpeckerci/plugin-release
    name: update-release
    settings:
      api_key:
        from_secret: FORGEJO_TOKEN
      note: Release is ready.
      overwrite: true
      title: ${CI_COMMIT_TAG}

  - commands:
      - git clone https://$${FORGEJO_USER}:$${FORGEJO_TOKEN}@code.unius.sh/${CI_REPO_OWNER}/poeticmetric-infrastructure.git infrastructure
      - cd infrastructure
      - git tag "${CI_COMMIT_TAG}"
      - git push --tags
    depends_on:
      - build-backend-image
      - build-frontend-image
      - build-helm-chart
    environment:
      FORGEJO_TOKEN:
        from_secret: FORGEJO_TOKEN
      FORGEJO_USER:
        from_secret: FORGEJO_USER
    image: alpine/k8s:1.33.5
    name: tag-infrastructure

when:
  - event: tag
