env:
  DOCKER_SCAN_SUGGEST: false
name: Check
on:
  pull_request:
jobs:
  run-backend-tests:
    if: github.event.pull_request.draft == false
    name: Run backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull required images
        run: docker compose pull clickhouse postgres rabbitmq

      - name: Build development image
        run: make test-build

      - name: Run tests
        run: |
          cp .env.example .env
          make test

  run-frontend-tests:
    if: github.event.pull_request.draft == false
    name: Run frontend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tsc
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          reporter: github-pr-review
          workdir: frontend

      - name: Run eslint
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: '--ext .js,.ts,.tsx .'
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: nofilter
          workdir: frontend

      - name: Run stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          stylelint_input: '**/*.scss'
          workdir: frontend
