name: Run tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  run-frontend-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19.1.0'

      - name: Install dependencies
        run: yarn install

      - name: Run stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          stylelint_input: '**/*.scss'
          workdir: frontend

      - name: Run eslint
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: '--ext .js,.ts,.tsx .'
          fail_on_error: true
          filter_mode: nofilter
          workdir: frontend
