name: Run backend tests
on:
  pull_request:
    branches:
      - "**"
env:
  DOCKER_SCAN_SUGGEST: false
jobs:
  run-backend-tests:
    name: Run backend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.3'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull required images
        run: docker compose --env-file ./.env.test pull clickhouse postgres rabbitmq
        working-directory: backend

      - name: Build development image
        run: make test-build
        working-directory: backend

      - name: Run tests
        run: make test
        working-directory: backend
